// ============================================================
// EnglishDaily — DỮ LIỆU MỞ RỘNG (nạp sau data.js)
// 1) CHUNKS: cụm từ giao tiếp nguyên khối cho từng chủ đề (thực chiến)
// 2) EXTRA_VOCAB / EXTRA_PHRASES: bổ sung từ vựng + mẫu câu
// 3) 5 chủ đề "Thực chiến" xuyên suốt (kỹ năng sống còn khi giao tiếp)
// Cấu trúc chunk: c = cụm từ, m = nghĩa, use = khi nào dùng, ex = ví dụ đối đáp
// ============================================================

const CHUNKS = {
greetings: [
  { c: "How's it going?", m: "dạo này sao rồi?", use: "hỏi thăm thân mật thay cho How are you", ex: "Hey Nam! How's it going? — Pretty good, thanks!" },
  { c: "Nice to meet you too", m: "mình cũng rất vui được gặp bạn", use: "đáp lại khi ai đó nói Nice to meet you", ex: "Nice to meet you! — Nice to meet you too!" },
  { c: "I'm Duong, by the way", m: "nhân tiện, mình là Dương", use: "tự giới thiệu tên giữa cuộc trò chuyện", ex: "Great game! I'm Duong, by the way." },
  { c: "This is my friend, ...", m: "đây là bạn của mình, ...", use: "giới thiệu người đi cùng", ex: "This is my friend, Lan. We work together." },
  { c: "Have a nice day!", m: "chúc một ngày tốt lành!", use: "chào tạm biệt lịch sự (cửa hàng, đồng nghiệp)", ex: "Goodbye! Have a nice day! — You too!" },
  { c: "See you around", m: "hẹn gặp lại quanh đây", use: "tạm biệt thân mật khi sẽ còn gặp lại", ex: "I have to go. See you around!" },
  { c: "Take care!", m: "bảo trọng nhé!", use: "tạm biệt kèm quan tâm", ex: "Bye Mom! — Take care, my dear!" },
  { c: "Welcome to ...", m: "chào mừng đến ...", use: "chào đón khách đến nơi của mình", ex: "Welcome to Vietnam! Is this your first visit?" },
],
family: [
  { c: "a family of five", m: "gia đình 5 người", use: "nói quy mô gia đình", ex: "We're a family of five: my parents, two brothers and me." },
  { c: "the youngest of three", m: "con út trong ba anh em", use: "nói thứ tự trong nhà", ex: "I'm the youngest of three children." },
  { c: "get along well with ...", m: "hòa thuận, hợp nhau với ...", use: "nói về quan hệ tốt", ex: "I get along well with my sister." },
  { c: "take after ...", m: "giống (bố/mẹ) về ngoại hình/tính cách", use: "nói con giống cha mẹ", ex: "Everyone says I take after my mother." },
  { c: "an only child", m: "con một", use: "nói mình không có anh chị em", ex: "Are you an only child? — Yes, I am." },
  { c: "on my mother's side", m: "bên ngoại", use: "phân biệt họ hàng bên nội/ngoại", ex: "My cousins on my mother's side live nearby." },
  { c: "We're very close", m: "chúng tôi rất thân nhau", use: "nói về sự gắn bó", ex: "My brother and I are very close." },
  { c: "grow up", m: "lớn lên", use: "kể về tuổi thơ, quê quán", ex: "I grew up in a small town in Ca Mau." },
],
"numbers-time": [
  { c: "a quarter to seven", m: "bảy giờ kém mười lăm", use: "nói giờ kém", ex: "The bus leaves at a quarter to seven." },
  { c: "in the morning / at night", m: "vào buổi sáng / ban đêm", use: "giới từ thời gian chuẩn cho các buổi", ex: "I study English in the morning and relax at night." },
  { c: "on time", m: "đúng giờ", use: "khen/nhắc về giờ giấc", ex: "The train is always on time here." },
  { c: "I'm running late", m: "mình đang bị trễ", use: "báo trước khi đến muộn", ex: "Sorry, I'm running late. Give me 10 minutes!" },
  { c: "in five minutes", m: "trong 5 phút nữa", use: "hẹn thời gian sắp tới", ex: "The meeting starts in five minutes." },
  { c: "the day after tomorrow", m: "ngày kia", use: "nói về 2 ngày sau", ex: "My exam is the day after tomorrow." },
  { c: "once a week", m: "mỗi tuần một lần", use: "nói tần suất", ex: "I visit my grandparents once a week." },
  { c: "It takes about ...", m: "mất khoảng ... (thời gian)", use: "ước lượng thời gian di chuyển/làm việc", ex: "It takes about 20 minutes by motorbike." },
],
"daily-routine": [
  { c: "first thing in the morning", m: "việc đầu tiên buổi sáng", use: "nhấn mạnh việc làm ngay khi thức dậy", ex: "I drink a glass of water first thing in the morning." },
  { c: "get ready for ...", m: "chuẩn bị cho ...", use: "nói về việc sửa soạn", ex: "I need 30 minutes to get ready for work." },
  { c: "do the dishes", m: "rửa bát", use: "việc nhà hằng ngày", ex: "It's your turn to do the dishes tonight!" },
  { c: "take out the trash", m: "đổ rác", use: "việc nhà hằng ngày", ex: "Don't forget to take out the trash." },
  { c: "make the bed", m: "dọn giường", use: "việc nhà buổi sáng", ex: "I make the bed right after waking up." },
  { c: "stay up late", m: "thức khuya", use: "nói về thói quen ngủ muộn", ex: "I stayed up late watching football last night." },
  { c: "have a day off", m: "có ngày nghỉ", use: "nói về ngày không đi làm/học", ex: "I have a day off tomorrow. Let's go somewhere!" },
  { c: "as usual", m: "như thường lệ", use: "nói việc lặp lại quen thuộc", ex: "I got up at six, as usual." },
],
food: [
  { c: "I'll have ...", m: "cho tôi món ...", use: "cách gọi món chuẩn và tự nhiên nhất", ex: "I'll have the beef noodles, please." },
  { c: "For here or to go?", m: "ăn tại chỗ hay mang về?", use: "câu nhân viên luôn hỏi ở quán ăn nhanh", ex: "For here or to go? — To go, please." },
  { c: "Could we get the bill?", m: "cho chúng tôi thanh toán", use: "xin tính tiền lịch sự", ex: "Excuse me, could we get the bill?" },
  { c: "It's on me", m: "để mình mời (mình trả)", use: "giành trả tiền cho cả bàn", ex: "Put your wallet away — it's on me today!" },
  { c: "I'm allergic to ...", m: "tôi bị dị ứng với ...", use: "báo dị ứng khi gọi món — rất quan trọng", ex: "I'm allergic to peanuts. Does this dish have any?" },
  { c: "No ice, please", m: "không cho đá nhé", use: "yêu cầu riêng khi gọi đồ uống", ex: "One orange juice, no ice, please." },
  { c: "Keep the change", m: "khỏi thối tiền", use: "boa lịch sự khi trả tiền mặt", ex: "Here's twenty. Keep the change!" },
  { c: "I'm full", m: "mình no rồi", use: "từ chối khéo khi được mời thêm", ex: "More rice? — No thanks, I'm full." },
],
shopping: [
  { c: "I'm just looking, thanks", m: "mình chỉ xem thôi, cảm ơn", use: "đáp khi nhân viên hỏi cần giúp gì — câu cứu cánh số 1 khi đi mua sắm", ex: "Can I help you? — I'm just looking, thanks." },
  { c: "Do you have this in ...?", m: "có cái này màu/cỡ ... không?", use: "hỏi phiên bản khác của món đồ", ex: "Do you have this in black? And in size L?" },
  { c: "It doesn't fit", m: "không vừa", use: "nói sau khi mặc thử", ex: "It doesn't fit. Do you have a bigger one?" },
  { c: "Can I get a refund?", m: "tôi được hoàn tiền không?", use: "trả hàng lấy lại tiền", ex: "This is broken. Can I get a refund?" },
  { c: "on sale", m: "đang giảm giá", use: "nói về khuyến mãi", ex: "These shoes are on sale — 50% off!" },
  { c: "out of stock", m: "hết hàng", use: "nhân viên hay nói khi hàng không còn", ex: "Sorry, that model is out of stock." },
  { c: "That's a rip-off!", m: "đắt cắt cổ!", use: "than giá quá đắt (thân mật, nói với bạn)", ex: "Ten dollars for a coffee? That's a rip-off!" },
  { c: "I'll think about it", m: "để mình suy nghĩ thêm", use: "từ chối khéo khi chưa muốn mua", ex: "It's nice, but I'll think about it." },
],
directions: [
  { c: "on your left / right", m: "phía bên trái / phải của bạn", use: "chỉ vị trí khi dẫn đường", ex: "Go straight and the bank is on your left." },
  { c: "go past ...", m: "đi qua ...", use: "chỉ đường qua một mốc", ex: "Go past the church and turn right." },
  { c: "It's just around the corner", m: "ngay góc phố thôi", use: "nói nơi cần tìm rất gần", ex: "The pharmacy? It's just around the corner." },
  { c: "You can't miss it", m: "dễ thấy lắm, không lạc được đâu", use: "trấn an sau khi chỉ đường", ex: "It's a big red building. You can't miss it." },
  { c: "I'm looking for ...", m: "tôi đang tìm ...", use: "mở đầu khi hỏi đường/tìm chỗ", ex: "Excuse me, I'm looking for the post office." },
  { c: "Is this the right way to ...?", m: "đi đường này đến ... đúng không?", use: "xác nhận lại hướng đi", ex: "Is this the right way to the beach?" },
  { c: "take the first turning on the left", m: "rẽ vào lối rẽ đầu tiên bên trái", use: "chỉ đường chi tiết", ex: "Take the first turning on the left after the bridge." },
  { c: "I'm a stranger here myself", m: "mình cũng không phải người ở đây", use: "đáp khi được hỏi đường mà không biết", ex: "Sorry, I'm a stranger here myself." },
],
weather: [
  { c: "It looks like rain", m: "trời trông như sắp mưa", use: "dự đoán khi nhìn trời", ex: "It looks like rain. Take your raincoat!" },
  { c: "boiling hot", m: "nóng như đổ lửa", use: "than trời quá nóng", ex: "It's boiling hot today — nearly 40 degrees!" },
  { c: "freezing cold", m: "lạnh cóng", use: "than trời quá lạnh", ex: "Close the window! It's freezing cold in here." },
  { c: "It's pouring", m: "mưa như trút nước", use: "tả mưa rất to", ex: "Don't go out now — it's pouring!" },
  { c: "clear up", m: "trời hửng, tạnh ráo", use: "nói trời đẹp trở lại", ex: "The sky should clear up this afternoon." },
  { c: "What's the forecast for tomorrow?", m: "dự báo ngày mai thế nào?", use: "hỏi thời tiết để lên kế hoạch", ex: "What's the forecast for tomorrow? — Sunny all day!" },
  { c: "Nice day, isn't it?", m: "trời đẹp nhỉ?", use: "câu bắt chuyện kinh điển với người lạ", ex: "Nice day, isn't it? — Yes, beautiful!" },
  { c: "get caught in the rain", m: "bị mắc mưa", use: "kể chuyện dính mưa", ex: "I got caught in the rain on my way home." },
],
hobbies: [
  { c: "I'm into ...", m: "mình đang mê ...", use: "nói sở thích một cách tự nhiên", ex: "I'm into photography these days." },
  { c: "I'm a big fan of ...", m: "mình là fan bự của ...", use: "bày tỏ sự yêu thích mạnh", ex: "I'm a big fan of Son Tung's music." },
  { c: "in my free time", m: "vào lúc rảnh", use: "mở đầu khi kể sở thích", ex: "In my free time, I play guitar and read." },
  { c: "I can't stand ...", m: "mình chịu không nổi ...", use: "nói điều mình ghét", ex: "I can't stand horror movies!" },
  { c: "It helps me relax", m: "nó giúp mình thư giãn", use: "giải thích vì sao thích", ex: "I love gardening. It helps me relax." },
  { c: "I've been doing it for ...", m: "mình theo nó được ... rồi", use: "nói thời gian gắn bó với sở thích", ex: "Chess? I've been playing it for five years." },
  { c: "Wanna join me?", m: "tham gia cùng mình không?", use: "rủ rê thân mật", ex: "I'm going fishing on Sunday. Wanna join me?" },
  { c: "It's not my thing", m: "không hợp gu mình", use: "từ chối khéo một hoạt động", ex: "Karaoke? Sorry, it's not really my thing." },
],
work: [
  { c: "I work as a ...", m: "tôi làm nghề ...", use: "giới thiệu nghề nghiệp", ex: "I work as a math teacher." },
  { c: "I'm in charge of ...", m: "tôi phụ trách ...", use: "nói về trách nhiệm công việc", ex: "I'm in charge of the youth union at school." },
  { c: "work overtime", m: "tăng ca", use: "nói về làm thêm giờ", ex: "I have to work overtime this week." },
  { c: "meet the deadline", m: "kịp hạn chót", use: "nói về áp lực công việc", ex: "We worked all night to meet the deadline." },
  { c: "take a day off", m: "xin nghỉ một ngày", use: "xin nghỉ phép", ex: "Can I take a day off on Friday?" },
  { c: "a nine-to-five job", m: "công việc hành chính giờ cố định", use: "mô tả kiểu công việc", ex: "I want more freedom than a nine-to-five job." },
  { c: "get a raise", m: "được tăng lương", use: "tin vui trong công việc", ex: "Great news — I got a raise this month!" },
  { c: "I'm swamped", m: "mình ngập trong việc", use: "than bận (thân mật)", ex: "Coffee later? — Sorry, I'm swamped today." },
],
health: [
  { c: "I feel under the weather", m: "thấy hơi ốm trong người", use: "nói mình không khỏe (nhẹ)", ex: "I feel a bit under the weather today." },
  { c: "come down with a cold", m: "bị cảm", use: "nói mình mới nhiễm bệnh", ex: "I think I'm coming down with a cold." },
  { c: "have a sore throat", m: "bị đau họng", use: "mô tả triệu chứng", ex: "I have a sore throat and a cough." },
  { c: "take medicine after meals", m: "uống thuốc sau bữa ăn", use: "hiểu lời dặn của bác sĩ", ex: "Take this medicine after meals, twice a day." },
  { c: "make an appointment with the doctor", m: "đặt lịch khám bác sĩ", use: "gọi điện đặt lịch khám", ex: "I'd like to make an appointment with Dr. Lee." },
  { c: "Get well soon!", m: "mau khỏe nhé!", use: "chúc người ốm", ex: "I heard you're sick. Get well soon!" },
  { c: "have a runny nose", m: "bị sổ mũi", use: "mô tả triệu chứng", ex: "I have a runny nose and I keep sneezing." },
  { c: "It hurts here", m: "đau ở chỗ này", use: "chỉ chỗ đau cho bác sĩ", ex: "It hurts here when I press it." },
],
phone: [
  { c: "Hold on a second", m: "chờ chút nhé", use: "xin người gọi đợi", ex: "Hold on a second, I'll get a pen." },
  { c: "You're breaking up", m: "sóng chập chờn, nghe không rõ", use: "báo tín hiệu kém khi gọi điện", ex: "Sorry, you're breaking up. Can you call again?" },
  { c: "I'll call you back", m: "mình sẽ gọi lại", use: "hẹn gọi lại khi đang bận", ex: "I'm in a meeting. I'll call you back in an hour." },
  { c: "Who's calling, please?", m: "xin hỏi ai đang gọi ạ?", use: "hỏi danh tính người gọi (lịch sự)", ex: "Hello? Who's calling, please?" },
  { c: "Can I take a message?", m: "anh/chị cần nhắn gì không?", use: "khi người được gọi vắng mặt", ex: "She's out now. Can I take a message?" },
  { c: "Sorry, wrong number", m: "xin lỗi, nhầm số rồi", use: "khi nhận cuộc gọi nhầm", ex: "Is this Mai's shop? — Sorry, wrong number." },
  { c: "Speaking!", m: "chính tôi đây!", use: "khi người gọi hỏi đúng tên mình", ex: "May I speak to Mr. Duong? — Speaking!" },
  { c: "Let's set up a meeting", m: "mình hẹn lịch gặp nhé", use: "chốt lịch hẹn qua điện thoại", ex: "Let's set up a meeting for next Monday." },
],
travel: [
  { c: "I have a reservation under ...", m: "tôi có đặt chỗ dưới tên ...", use: "nhận phòng/bàn đã đặt trước", ex: "I have a reservation under Duong." },
  { c: "a round-trip ticket", m: "vé khứ hồi", use: "mua vé máy bay/tàu xe", ex: "A round-trip ticket to Hanoi, please." },
  { c: "Window or aisle seat?", m: "ghế cửa sổ hay lối đi?", use: "câu hay gặp khi check-in máy bay", ex: "Window or aisle seat? — Window, please!" },
  { c: "Is breakfast included?", m: "có kèm bữa sáng không?", use: "hỏi khi nhận phòng khách sạn", ex: "Is breakfast included in the price?" },
  { c: "Could you call a taxi for me?", m: "gọi giúp tôi taxi được không?", use: "nhờ lễ tân khách sạn", ex: "Could you call a taxi for me? I'm going to the airport." },
  { c: "What time is check-out?", m: "mấy giờ trả phòng?", use: "hỏi giờ trả phòng", ex: "What time is check-out? — Twelve o'clock, sir." },
  { c: "travel light", m: "đi du lịch gọn nhẹ", use: "nói về phong cách xếp hành lý", ex: "I always travel light — just one backpack." },
  { c: "get lost", m: "bị lạc đường", use: "kể chuyện/nhờ giúp khi lạc", ex: "We got lost in the old town for two hours!" },
],
feelings: [
  { c: "I'm over the moon", m: "mình vui sướng tột độ", use: "bày tỏ niềm vui lớn", ex: "I passed the exam! I'm over the moon!" },
  { c: "I'm fed up with ...", m: "mình chán ngấy ... rồi", use: "bày tỏ sự chán chường", ex: "I'm fed up with this hot weather." },
  { c: "Calm down", m: "bình tĩnh nào", use: "trấn an người đang nóng giận/lo lắng", ex: "Calm down and tell me what happened." },
  { c: "Cheer up!", m: "vui lên nào!", use: "an ủi người đang buồn", ex: "Cheer up! Tomorrow is another day." },
  { c: "It's not a big deal", m: "chuyện nhỏ mà, không có gì to tát", use: "xoa dịu, giảm nhẹ vấn đề", ex: "Sorry about the cup! — It's not a big deal." },
  { c: "I know how you feel", m: "mình hiểu cảm giác của bạn", use: "đồng cảm với người khác", ex: "I failed again... — I know how you feel." },
  { c: "I can't wait!", m: "nóng lòng quá đi!", use: "bày tỏ sự háo hức", ex: "The trip is next week. I can't wait!" },
  { c: "It drives me crazy", m: "nó làm mình phát điên", use: "than phiền điều gây khó chịu", ex: "The noise next door drives me crazy!" },
],
money: [
  { c: "pay in cash / by card", m: "trả bằng tiền mặt / bằng thẻ", use: "nói cách thanh toán", ex: "Will you pay in cash or by card?" },
  { c: "How would you like to pay?", m: "anh/chị muốn thanh toán bằng gì?", use: "câu thu ngân luôn hỏi", ex: "How would you like to pay? — By card, please." },
  { c: "save up for ...", m: "để dành tiền mua ...", use: "nói về mục tiêu tiết kiệm", ex: "I'm saving up for a new laptop." },
  { c: "on a tight budget", m: "kinh phí eo hẹp", use: "nói mình đang phải tằn tiện", ex: "We're on a tight budget this month." },
  { c: "split the bill", m: "chia đôi hóa đơn, ai ăn nấy trả", use: "đề nghị chia tiền khi ăn chung", ex: "Let's split the bill, OK?" },
  { c: "It costs a fortune", m: "đắt khủng khiếp", use: "than món đồ quá đắt", ex: "That new iPhone costs a fortune!" },
  { c: "worth the money", m: "đáng đồng tiền", use: "nhận xét món đồ xứng giá", ex: "Expensive, but really worth the money." },
  { c: "run out of money", m: "hết sạch tiền", use: "nói tình trạng cạn túi", ex: "I ran out of money before the end of the month." },
],
study: [
  { c: "learn ... by heart", m: "học thuộc lòng ...", use: "nói về cách học ghi nhớ", ex: "I learned the whole poem by heart." },
  { c: "make progress", m: "tiến bộ", use: "nhận xét sự tiến bộ trong học tập", ex: "Your English is making great progress!" },
  { c: "hand in homework", m: "nộp bài tập", use: "trong lớp học", ex: "Please hand in your homework by Friday." },
  { c: "pass / fail an exam", m: "thi đỗ / thi trượt", use: "nói kết quả thi", ex: "I passed the driving exam on my first try!" },
  { c: "look it up", m: "tra (từ điển/mạng)", use: "khi gặp từ không biết", ex: "I don't know this word. Let me look it up." },
  { c: "Practice makes perfect", m: "có công mài sắt có ngày nên kim", use: "động viên người đang luyện tập", ex: "Keep speaking every day — practice makes perfect!" },
  { c: "take notes", m: "ghi chú, ghi chép", use: "trong lớp/cuộc họp", ex: "I always take notes during the lesson." },
  { c: "I'm getting better at ...", m: "mình đang khá lên về ...", use: "tự nhận xét sự tiến bộ", ex: "I'm getting better at listening to English." },
],
sports: [
  { c: "work out", m: "tập luyện thể hình", use: "nói về việc tập gym", ex: "I work out at the gym three times a week." },
  { c: "stay in shape", m: "giữ dáng, giữ thể lực", use: "nói mục đích tập luyện", ex: "I jog every morning to stay in shape." },
  { c: "warm up", m: "khởi động", use: "trước khi tập/thi đấu", ex: "Always warm up before you run." },
  { c: "beat ...", m: "thắng, đánh bại ...", use: "nói kết quả trận đấu", ex: "We beat their team 3-1!" },
  { c: "What's the score?", m: "tỷ số bao nhiêu rồi?", use: "hỏi khi vào xem giữa trận", ex: "What's the score? — Two-nil for Vietnam!" },
  { c: "play against ...", m: "thi đấu với ...", use: "nói về đối thủ", ex: "We're playing against Thailand tonight." },
  { c: "Give it your best shot", m: "cố hết sức nhé", use: "động viên trước thử thách", ex: "The final is tomorrow. Give it your best shot!" },
  { c: "I'm out of breath", m: "mình hụt hơi rồi", use: "sau khi vận động mạnh", ex: "Wait... I'm out of breath after those stairs!" },
],
party: [
  { c: "Are you free on ...?", m: "bạn có rảnh vào ... không?", use: "bước 1 của mọi lời mời", ex: "Are you free on Saturday night?" },
  { c: "I'd love to!", m: "mình rất thích! (đồng ý)", use: "nhận lời mời nhiệt tình", ex: "Come to my party! — I'd love to!" },
  { c: "I'm afraid I can't make it", m: "tiếc là mình không đến được", use: "từ chối lời mời lịch sự", ex: "I'm afraid I can't make it on Sunday. I'm so sorry!" },
  { c: "Help yourself!", m: "cứ tự nhiên nhé! (mời ăn uống)", use: "chủ nhà mời khách", ex: "The food is ready. Help yourself!" },
  { c: "Cheers!", m: "cạn ly!", use: "nâng ly chúc mừng", ex: "To your new job — cheers!" },
  { c: "throw a party", m: "mở tiệc", use: "nói về việc tổ chức tiệc", ex: "We're throwing a party for Dad's birthday." },
  { c: "Thanks for having me", m: "cảm ơn đã mời/tiếp đón mình", use: "cảm ơn chủ nhà khi ra về", ex: "Great evening! Thanks for having me." },
  { c: "I had a great time", m: "mình đã rất vui", use: "khen buổi tiệc khi chia tay", ex: "I had a great time tonight. See you soon!" },
],
technology: [
  { c: "My phone is dead", m: "điện thoại mình sập nguồn rồi", use: "giải thích vì sao mất liên lạc", ex: "Sorry I missed your call — my phone was dead." },
  { c: "run out of battery", m: "cạn pin", use: "báo sắp hết pin", ex: "My phone is running out of battery. Text me instead!" },
  { c: "turn it off and on again", m: "tắt đi bật lại", use: "cách sửa lỗi công nghệ kinh điển", ex: "The app froze? Turn it off and on again." },
  { c: "It's not working", m: "nó không hoạt động", use: "báo thiết bị/phần mềm bị lỗi", ex: "The printer is not working again!" },
  { c: "log in / log out", m: "đăng nhập / đăng xuất", use: "dùng ứng dụng, trang web", ex: "Log in with your email and password." },
  { c: "Send me the link", m: "gửi mình cái link nhé", use: "xin đường dẫn qua chat", ex: "That video sounds fun — send me the link!" },
  { c: "on silent mode", m: "đang ở chế độ im lặng", use: "giải thích vì sao không nghe máy", ex: "Sorry, my phone was on silent mode." },
  { c: "Add me on ...", m: "kết bạn với mình trên ... nhé", use: "xin kết nối mạng xã hội", ex: "Add me on Facebook! Here's my name." },
],
emergency: [
  { c: "Call the police!", m: "gọi cảnh sát đi!", use: "hô hoán khẩn cấp", ex: "He took my bag! Call the police!" },
  { c: "It's an emergency!", m: "chuyện khẩn cấp!", use: "nhấn mạnh mức độ nghiêm trọng", ex: "Open the door, please. It's an emergency!" },
  { c: "I lost my ...", m: "tôi bị mất ...", use: "trình báo mất đồ", ex: "I lost my passport this morning." },
  { c: "Watch out!", m: "coi chừng!", use: "cảnh báo nguy hiểm tức thì", ex: "Watch out! The floor is wet!" },
  { c: "Are you OK?", m: "bạn ổn không?", use: "hỏi thăm người vừa gặp sự cố", ex: "You fell! Are you OK?" },
  { c: "I need help right now", m: "tôi cần giúp đỡ ngay bây giờ", use: "yêu cầu hỗ trợ khẩn", ex: "Please, I need help right now — my friend fainted!" },
  { c: "Someone stole my ...", m: "ai đó đã trộm ... của tôi", use: "trình báo bị trộm", ex: "Someone stole my wallet on the bus." },
  { c: "Where is the nearest hospital?", m: "bệnh viện gần nhất ở đâu?", use: "hỏi đường khẩn cấp", ex: "Where is the nearest hospital? My son is sick!" },
],
smalltalk: [
  { c: "How have you been?", m: "dạo này bạn thế nào?", use: "hỏi thăm người lâu không gặp", ex: "Duong! How have you been? — Great, and you?" },
  { c: "What's new?", m: "có gì mới không?", use: "mở chuyện thân mật", ex: "Hey! What's new? — Not much, same old!" },
  { c: "Same as usual", m: "vẫn như mọi khi", use: "đáp khi không có gì mới", ex: "How's work? — Same as usual, busy busy." },
  { c: "It was nice talking to you", m: "rất vui được trò chuyện với bạn", use: "kết thúc cuộc trò chuyện lịch sự", ex: "I have to run. It was nice talking to you!" },
  { c: "Let's grab a coffee sometime", m: "bữa nào đi cà phê nhé", use: "hẹn gặp không chính thức", ex: "Let's grab a coffee sometime! — Sure, text me." },
  { c: "Say hi to ... for me", m: "cho mình gửi lời chào tới ...", use: "gửi lời hỏi thăm qua người khác", ex: "Say hi to your parents for me!" },
  { c: "Guess what?", m: "đoán xem có chuyện gì nào?", use: "mở đầu khi sắp kể tin hot", ex: "Guess what? I'm getting married!" },
  { c: "Time flies!", m: "thời gian trôi nhanh thật!", use: "cảm thán khi nhắc kỷ niệm cũ", ex: "Ten years since high school... Time flies!" },
],
};

// ===== TỪ VỰNG BỔ SUNG =====
const EXTRA_VOCAB = {
greetings: [
  { w: "introduce", ipa: "/ˌɪntrəˈduːs/", m: "giới thiệu", ex: "Let me introduce myself." },
  { w: "polite", ipa: "/pəˈlaɪt/", m: "lịch sự", ex: "He is always polite to everyone." },
  { w: "shake hands", ipa: "/ʃeɪk hændz/", m: "bắt tay", ex: "They shook hands and smiled." },
  { w: "stranger", ipa: "/ˈstreɪndʒər/", m: "người lạ", ex: "Don't be shy with strangers — say hello!" },
],
family: [
  { w: "cousin", ipa: "/ˈkʌzn/", m: "anh/chị/em họ", ex: "My cousin lives in Ho Chi Minh City." },
  { w: "uncle", ipa: "/ˈʌŋkl/", m: "chú, bác, cậu", ex: "My uncle is a farmer." },
  { w: "aunt", ipa: "/ænt/", m: "cô, dì, thím", ex: "Aunt Hoa makes the best spring rolls." },
  { w: "relative", ipa: "/ˈrelətɪv/", m: "họ hàng", ex: "All my relatives come home for Tet." },
],
"numbers-time": [
  { w: "midnight", ipa: "/ˈmɪdnaɪt/", m: "nửa đêm", ex: "The party ended at midnight." },
  { w: "noon", ipa: "/nuːn/", m: "buổi trưa (12h)", ex: "Let's meet at noon for lunch." },
  { w: "schedule", ipa: "/ˈskedʒuːl/", m: "lịch trình", ex: "My schedule is full this week." },
  { w: "moment", ipa: "/ˈmoʊmənt/", m: "khoảnh khắc, chốc lát", ex: "Wait a moment, please." },
],
"daily-routine": [
  { w: "laundry", ipa: "/ˈlɔːndri/", m: "quần áo giặt, việc giặt giũ", ex: "I do the laundry on Saturdays." },
  { w: "nap", ipa: "/næp/", m: "giấc ngủ trưa/ngắn", ex: "I take a short nap after lunch." },
  { w: "alarm clock", ipa: "/əˈlɑːrm klɑːk/", m: "đồng hồ báo thức", ex: "My alarm clock rings at 5:30." },
  { w: "tidy", ipa: "/ˈtaɪdi/", m: "gọn gàng; dọn dẹp", ex: "Keep your desk tidy." },
],
food: [
  { w: "tasty", ipa: "/ˈteɪsti/", m: "ngon miệng", ex: "This soup is really tasty." },
  { w: "sour", ipa: "/ˈsaʊər/", m: "chua", ex: "The soup is a little sour — I love it." },
  { w: "sweet", ipa: "/swiːt/", m: "ngọt", ex: "This tea is too sweet for me." },
  { w: "seafood", ipa: "/ˈsiːfuːd/", m: "hải sản", ex: "Ca Mau is famous for fresh seafood." },
],
shopping: [
  { w: "brand", ipa: "/brænd/", m: "thương hiệu", ex: "Which brand do you like best?" },
  { w: "fitting room", ipa: "/ˈfɪtɪŋ ruːm/", m: "phòng thử đồ", ex: "The fitting room is over there." },
  { w: "refund", ipa: "/ˈriːfʌnd/", m: "hoàn tiền", ex: "They gave me a full refund." },
  { w: "customer", ipa: "/ˈkʌstəmər/", m: "khách hàng", ex: "The customer is always right." },
],
directions: [
  { w: "map", ipa: "/mæp/", m: "bản đồ", ex: "Let me check the map on my phone." },
  { w: "corner", ipa: "/ˈkɔːrnər/", m: "góc phố", ex: "The café is on the corner." },
  { w: "bridge", ipa: "/brɪdʒ/", m: "cây cầu", ex: "Cross the bridge and turn left." },
  { w: "opposite", ipa: "/ˈɑːpəzɪt/", m: "đối diện", ex: "The bank is opposite the market." },
],
weather: [
  { w: "storm", ipa: "/stɔːrm/", m: "bão", ex: "A big storm is coming this weekend." },
  { w: "humid", ipa: "/ˈhjuːmɪd/", m: "ẩm, oi", ex: "Summer here is hot and humid." },
  { w: "sunshine", ipa: "/ˈsʌnʃaɪn/", m: "ánh nắng", ex: "We need some sunshine after all this rain." },
  { w: "season", ipa: "/ˈsiːzn/", m: "mùa", ex: "The rainy season starts in May." },
],
hobbies: [
  { w: "painting", ipa: "/ˈpeɪntɪŋ/", m: "vẽ tranh", ex: "She took up painting last year." },
  { w: "gardening", ipa: "/ˈɡɑːrdnɪŋ/", m: "làm vườn", ex: "Gardening keeps my dad happy." },
  { w: "chess", ipa: "/tʃes/", m: "cờ vua", ex: "Do you play chess?" },
  { w: "camping", ipa: "/ˈkæmpɪŋ/", m: "cắm trại", ex: "We go camping every summer." },
],
work: [
  { w: "boss", ipa: "/bɔːs/", m: "sếp", ex: "My boss is quite friendly." },
  { w: "staff", ipa: "/stæf/", m: "nhân viên", ex: "The staff here are very helpful." },
  { w: "shift", ipa: "/ʃɪft/", m: "ca làm việc", ex: "I work the night shift this week." },
  { w: "retire", ipa: "/rɪˈtaɪər/", m: "nghỉ hưu", ex: "My father retired last year." },
],
health: [
  { w: "dizzy", ipa: "/ˈdɪzi/", m: "chóng mặt", ex: "I feel dizzy when I stand up fast." },
  { w: "stomachache", ipa: "/ˈstʌməkeɪk/", m: "đau bụng", ex: "I have a stomachache after lunch." },
  { w: "allergy", ipa: "/ˈælərdʒi/", m: "dị ứng", ex: "Do you have any allergies?" },
  { w: "flu", ipa: "/fluː/", m: "cúm", ex: "Half the class is off with the flu." },
],
phone: [
  { w: "voicemail", ipa: "/ˈvɔɪsmeɪl/", m: "hộp thư thoại", ex: "Leave a voicemail after the beep." },
  { w: "missed call", ipa: "/mɪst kɔːl/", m: "cuộc gọi nhỡ", ex: "I have three missed calls from you!" },
  { w: "contact", ipa: "/ˈkɑːntækt/", m: "danh bạ; liên hệ", ex: "I saved your number in my contacts." },
  { w: "text", ipa: "/tekst/", m: "nhắn tin", ex: "Text me when you arrive." },
],
travel: [
  { w: "visa", ipa: "/ˈviːzə/", m: "thị thực", ex: "Do I need a visa for Thailand?" },
  { w: "customs", ipa: "/ˈkʌstəmz/", m: "hải quan", ex: "We waited an hour at customs." },
  { w: "boarding pass", ipa: "/ˈbɔːrdɪŋ pæs/", m: "thẻ lên máy bay", ex: "Please show your boarding pass." },
  { w: "backpack", ipa: "/ˈbækpæk/", m: "ba lô", ex: "One backpack is enough for three days." },
],
feelings: [
  { w: "proud", ipa: "/praʊd/", m: "tự hào", ex: "I'm so proud of you!" },
  { w: "nervous", ipa: "/ˈnɜːrvəs/", m: "hồi hộp, lo lắng", ex: "I was nervous before the interview." },
  { w: "bored", ipa: "/bɔːrd/", m: "chán", ex: "The kids got bored after an hour." },
  { w: "grateful", ipa: "/ˈɡreɪtfl/", m: "biết ơn", ex: "I'm grateful for your help." },
],
money: [
  { w: "loan", ipa: "/loʊn/", m: "khoản vay", ex: "They took a loan to buy a house." },
  { w: "interest", ipa: "/ˈɪntrəst/", m: "tiền lãi", ex: "The bank pays 5% interest." },
  { w: "wallet", ipa: "/ˈwɑːlɪt/", m: "ví tiền", ex: "I left my wallet at home!" },
  { w: "income", ipa: "/ˈɪnkʌm/", m: "thu nhập", ex: "Her income doubled after the new job." },
],
study: [
  { w: "dictionary", ipa: "/ˈdɪkʃəneri/", m: "từ điển", ex: "Use a dictionary when you read." },
  { w: "mistake", ipa: "/mɪˈsteɪk/", m: "lỗi sai", ex: "Don't be afraid of making mistakes." },
  { w: "knowledge", ipa: "/ˈnɑːlɪdʒ/", m: "kiến thức", ex: "Reading builds your knowledge." },
  { w: "degree", ipa: "/dɪˈɡriː/", m: "bằng cấp", ex: "She has a degree in English." },
],
sports: [
  { w: "coach", ipa: "/koʊtʃ/", m: "huấn luyện viên", ex: "Our coach is very strict." },
  { w: "race", ipa: "/reɪs/", m: "cuộc đua", ex: "He won the race by two seconds." },
  { w: "muscle", ipa: "/ˈmʌsl/", m: "cơ bắp", ex: "My muscles hurt after the gym." },
  { w: "champion", ipa: "/ˈtʃæmpiən/", m: "nhà vô địch", ex: "Vietnam is the champion this year!" },
],
party: [
  { w: "anniversary", ipa: "/ˌænɪˈvɜːrsəri/", m: "ngày kỷ niệm", ex: "It's my parents' 30th anniversary." },
  { w: "host", ipa: "/hoʊst/", m: "chủ nhà, người tổ chức", ex: "The host welcomed everyone warmly." },
  { w: "firework", ipa: "/ˈfaɪərwɜːrk/", m: "pháo hoa", ex: "We watched fireworks at midnight." },
  { w: "dance", ipa: "/dæns/", m: "nhảy, khiêu vũ", ex: "Everyone danced until 2 a.m." },
],
technology: [
  { w: "screen", ipa: "/skriːn/", m: "màn hình", ex: "My screen is cracked." },
  { w: "app", ipa: "/æp/", m: "ứng dụng", ex: "This app helps me learn English." },
  { w: "headphones", ipa: "/ˈhedfoʊnz/", m: "tai nghe", ex: "I listen to podcasts with headphones." },
  { w: "signal", ipa: "/ˈsɪɡnəl/", m: "sóng, tín hiệu", ex: "There's no signal in the elevator." },
],
emergency: [
  { w: "danger", ipa: "/ˈdeɪndʒər/", m: "nguy hiểm", ex: "Danger! Do not enter." },
  { w: "injured", ipa: "/ˈɪndʒərd/", m: "bị thương", ex: "Two people were injured in the accident." },
  { w: "insurance", ipa: "/ɪnˈʃʊrəns/", m: "bảo hiểm", ex: "Travel insurance saved me a lot of money." },
  { w: "rescue", ipa: "/ˈreskjuː/", m: "cứu hộ", ex: "The rescue team arrived quickly." },
],
smalltalk: [
  { w: "neighbor", ipa: "/ˈneɪbər/", m: "hàng xóm", ex: "Our new neighbor is very friendly." },
  { w: "news", ipa: "/nuːz/", m: "tin tức", ex: "Have you heard the news about Minh?" },
  { w: "chat", ipa: "/tʃæt/", m: "trò chuyện phiếm", ex: "We had a nice chat over coffee." },
  { w: "joke", ipa: "/dʒoʊk/", m: "chuyện đùa", ex: "He always tells funny jokes." },
],
};

// ===== MẪU CÂU BỔ SUNG =====
const EXTRA_PHRASES = {
greetings: [
  { en: "How was your day?", vi: "Hôm nay của bạn thế nào?" },
  { en: "It's good to see you again.", vi: "Thật vui khi gặp lại bạn." },
  { en: "Have a good weekend!", vi: "Cuối tuần vui vẻ nhé!" },
],
family: [
  { en: "Who do you live with?", vi: "Bạn sống cùng ai?" },
  { en: "My parents are both retired.", vi: "Bố mẹ mình đều nghỉ hưu rồi." },
  { en: "We have dinner together every evening.", vi: "Nhà mình ăn tối cùng nhau mỗi ngày." },
],
"numbers-time": [
  { en: "Are you free this afternoon?", vi: "Chiều nay bạn rảnh không?" },
  { en: "I'll be there in ten minutes.", vi: "Mười phút nữa mình tới." },
  { en: "What time do you finish work?", vi: "Mấy giờ bạn tan làm?" },
],
"daily-routine": [
  { en: "I usually cook dinner myself.", vi: "Mình thường tự nấu bữa tối." },
  { en: "How do you get to work?", vi: "Bạn đi làm bằng gì?" },
  { en: "I spend the evening with my family.", vi: "Buổi tối mình dành cho gia đình." },
],
food: [
  { en: "Is this dish spicy?", vi: "Món này có cay không?" },
  { en: "Could I have some more water?", vi: "Cho tôi thêm chút nước được không?" },
  { en: "Everything was delicious, thank you!", vi: "Mọi món đều ngon, cảm ơn!" },
],
shopping: [
  { en: "Where can I pay?", vi: "Tôi thanh toán ở đâu?" },
  { en: "Do you have anything cheaper?", vi: "Có món nào rẻ hơn không?" },
  { en: "I'm looking for a gift for my friend.", vi: "Mình đang tìm quà cho bạn." },
],
directions: [
  { en: "Can you show me on the map?", vi: "Chỉ giúp tôi trên bản đồ được không?" },
  { en: "How long does it take to walk there?", vi: "Đi bộ đến đó mất bao lâu?" },
  { en: "Is there a bus to the city center?", vi: "Có xe buýt đến trung tâm không?" },
],
weather: [
  { en: "It's much cooler than yesterday.", vi: "Hôm nay mát hơn hôm qua nhiều." },
  { en: "I hope it doesn't rain tomorrow.", vi: "Mong là mai đừng mưa." },
  { en: "The weather is perfect for a picnic.", vi: "Thời tiết này đi dã ngoại là tuyệt." },
],
hobbies: [
  { en: "How did you get into it?", vi: "Sao bạn lại mê món đó?" },
  { en: "We should do it together sometime.", vi: "Bữa nào mình làm chung đi." },
  { en: "I'm learning to play the piano.", vi: "Mình đang học chơi piano." },
],
work: [
  { en: "What time do you start work?", vi: "Mấy giờ bạn bắt đầu làm việc?" },
  { en: "I have a meeting all morning.", vi: "Cả sáng mình họp." },
  { en: "The new project starts next week.", vi: "Dự án mới bắt đầu tuần sau." },
],
health: [
  { en: "You should drink more water.", vi: "Bạn nên uống nhiều nước hơn." },
  { en: "How often do you exercise?", vi: "Bạn tập thể dục thường xuyên không?" },
  { en: "I need to see a dentist.", vi: "Tôi cần đi khám nha sĩ." },
],
phone: [
  { en: "Could you speak up a little?", vi: "Bạn nói to lên chút được không?" },
  { en: "I'll text you the address.", vi: "Mình sẽ nhắn địa chỉ cho bạn." },
  { en: "My battery is about to die.", vi: "Điện thoại mình sắp hết pin." },
],
travel: [
  { en: "Where is the check-in counter?", vi: "Quầy làm thủ tục ở đâu?" },
  { en: "How much is a taxi to the hotel?", vi: "Taxi về khách sạn hết bao nhiêu?" },
  { en: "Can I have a map of the city?", vi: "Cho tôi xin bản đồ thành phố?" },
],
feelings: [
  { en: "You look worried. What's wrong?", vi: "Trông bạn lo lắng thế. Có chuyện gì vậy?" },
  { en: "Don't worry, everything will be fine.", vi: "Đừng lo, mọi chuyện sẽ ổn thôi." },
  { en: "I'm really happy for you!", vi: "Mình thật sự mừng cho bạn!" },
],
money: [
  { en: "Can you lend me some money until Friday?", vi: "Cho mình vay ít tiền đến thứ Sáu nhé?" },
  { en: "Where can I change money?", vi: "Tôi đổi tiền ở đâu được?" },
  { en: "Do you accept credit cards?", vi: "Ở đây nhận thẻ tín dụng không?" },
],
study: [
  { en: "Can you say that again more slowly?", vi: "Bạn nói lại chậm hơn được không?" },
  { en: "What does this word mean?", vi: "Từ này nghĩa là gì?" },
  { en: "I study English thirty minutes a day.", vi: "Mình học tiếng Anh 30 phút mỗi ngày." },
],
sports: [
  { en: "Which team do you support?", vi: "Bạn cổ vũ đội nào?" },
  { en: "Do you want to play badminton this evening?", vi: "Tối nay đánh cầu lông không?" },
  { en: "That was a great match!", vi: "Trận đấu hay thật!" },
],
party: [
  { en: "What should I bring?", vi: "Mình nên mang gì đến?" },
  { en: "The party starts at seven.", vi: "Tiệc bắt đầu lúc bảy giờ." },
  { en: "Let's take a photo together!", vi: "Chụp chung tấm ảnh nào!" },
],
technology: [
  { en: "How do I install this app?", vi: "Cài ứng dụng này thế nào?" },
  { en: "The internet is really slow today.", vi: "Hôm nay mạng chậm quá." },
  { en: "Can I borrow your phone for a second?", vi: "Cho mình mượn điện thoại một lát nhé?" },
],
emergency: [
  { en: "Please call this number for me.", vi: "Làm ơn gọi số này giúp tôi." },
  { en: "I don't feel safe here.", vi: "Tôi thấy ở đây không an toàn." },
  { en: "Stay calm and follow me.", vi: "Bình tĩnh và đi theo tôi." },
],
smalltalk: [
  { en: "Did you watch the game last night?", vi: "Tối qua bạn xem trận đấu không?" },
  { en: "Any plans for the weekend?", vi: "Cuối tuần có kế hoạch gì chưa?" },
  { en: "I like your shirt! Where did you get it?", vi: "Áo đẹp đấy! Mua ở đâu vậy?" },
],
};

// ===== 5 CHỦ ĐỀ "THỰC CHIẾN" XUYÊN SUỐT =====
TOPICS.push(
{
  id: "survival-basics", icon: "🧰", level: 1,
  name: "Thực chiến: Câu cứu cánh",
  nameEn: "Survival English",
  vocab: [
    { w: "understand", ipa: "/ˌʌndərˈstænd/", m: "hiểu", ex: "I don't understand this sentence." },
    { w: "repeat", ipa: "/rɪˈpiːt/", m: "nhắc lại", ex: "Could you repeat that, please?" },
    { w: "slowly", ipa: "/ˈsloʊli/", m: "chậm rãi", ex: "Please speak slowly." },
    { w: "mean", ipa: "/miːn/", m: "có nghĩa là", ex: "What does this word mean?" },
    { w: "spell", ipa: "/spel/", m: "đánh vần", ex: "How do you spell your name?" },
    { w: "explain", ipa: "/ɪkˈspleɪn/", m: "giải thích", ex: "Can you explain it again?" },
  ],
  chunks: [
    { c: "Sorry?", m: "dạ, gì cơ ạ?", use: "cách ngắn nhất để xin nhắc lại", ex: "Blah blah... — Sorry? — I said turn left!" },
    { c: "Can you say that again, please?", m: "bạn nói lại được không?", use: "xin nhắc lại đầy đủ, lịch sự", ex: "Can you say that again, please? A bit slower?" },
    { c: "Please speak more slowly", m: "làm ơn nói chậm lại", use: "khi người bản xứ nói quá nhanh", ex: "My English is basic — please speak more slowly." },
    { c: "What does ... mean?", m: "... nghĩa là gì?", use: "hỏi nghĩa từ chưa biết", ex: "What does 'refund' mean?" },
    { c: "How do you say ... in English?", m: "... tiếng Anh nói thế nào?", use: "hỏi cách diễn đạt", ex: "How do you say 'nước mắm' in English?" },
    { c: "I don't understand", m: "tôi không hiểu", use: "nói thẳng để được giải thích lại", ex: "I don't understand. Can you show me?" },
    { c: "Could you write it down?", m: "bạn viết ra giúp được không?", use: "khi nghe không kịp (tên, địa chỉ, số)", ex: "Could you write it down for me? My listening is not good." },
    { c: "My English is not very good", m: "tiếng Anh của tôi chưa tốt lắm", use: "xin thông cảm trước khi trò chuyện", ex: "My English is not very good, but I'll try!" },
    { c: "Got it!", m: "hiểu rồi!", use: "xác nhận đã hiểu (thân mật)", ex: "Turn left at the bank. — Got it, thanks!" },
    { c: "Never mind", m: "thôi không sao đâu", use: "bỏ qua khi giải thích mãi không xong", ex: "You don't get it? Never mind, look at my map." },
  ],
  phrases: [
    { en: "Sorry, I didn't catch that.", vi: "Xin lỗi, mình nghe không kịp." },
    { en: "Could you explain that in a simple way?", vi: "Bạn giải thích đơn giản hơn được không?" },
    { en: "Is this correct?", vi: "Thế này đúng chưa?" },
    { en: "How do you pronounce this word?", vi: "Từ này phát âm thế nào?" },
    { en: "Let me check my dictionary.", vi: "Để mình tra từ điển đã." },
    { en: "Thank you for your patience.", vi: "Cảm ơn bạn đã kiên nhẫn với mình." },
  ],
  dialogue: [
    { who: "A", en: "The station is two blocks down, past the roundabout, next to the pharmacy.", vi: "Nhà ga cách đây hai dãy nhà, qua vòng xuyến, cạnh hiệu thuốc." },
    { who: "B", en: "Sorry? Can you say that again, please? My English is not very good.", vi: "Dạ gì cơ ạ? Bạn nói lại được không? Tiếng Anh mình chưa tốt lắm." },
    { who: "A", en: "Of course! Go straight... two streets... then you see a pharmacy.", vi: "Được chứ! Đi thẳng... hai con phố... rồi bạn sẽ thấy hiệu thuốc." },
    { who: "B", en: "What does 'pharmacy' mean?", vi: "'Pharmacy' nghĩa là gì vậy?" },
    { who: "A", en: "It's a shop for medicine. Here, I'll write it down for you.", vi: "Là cửa hàng bán thuốc. Đây, để mình viết ra cho bạn." },
    { who: "B", en: "Got it! Thank you so much for your patience!", vi: "Hiểu rồi! Cảm ơn bạn nhiều vì đã kiên nhẫn!" },
  ],
},
{
  id: "polite-requests", icon: "🙏", level: 1,
  name: "Thực chiến: Nhờ vả & lịch sự",
  nameEn: "Polite Requests",
  vocab: [
    { w: "favor", ipa: "/ˈfeɪvər/", m: "sự giúp đỡ, ân huệ", ex: "Can you do me a favor?" },
    { w: "bother", ipa: "/ˈbɑːðər/", m: "làm phiền", ex: "Sorry to bother you." },
    { w: "appreciate", ipa: "/əˈpriːʃieɪt/", m: "cảm kích", ex: "I really appreciate your help." },
    { w: "kind", ipa: "/kaɪnd/", m: "tốt bụng", ex: "That's very kind of you." },
    { w: "borrow", ipa: "/ˈbɑːroʊ/", m: "mượn", ex: "May I borrow your pen?" },
    { w: "of course", ipa: "/əv kɔːrs/", m: "tất nhiên rồi", ex: "Can you help? — Of course!" },
  ],
  chunks: [
    { c: "Could you help me, please?", m: "bạn giúp mình được không?", use: "câu nhờ vả an toàn trong mọi tình huống", ex: "Could you help me, please? This box is heavy." },
    { c: "Excuse me", m: "xin lỗi, cho hỏi...", use: "mở đầu để gây chú ý lịch sự", ex: "Excuse me, is this seat taken?" },
    { c: "Would you mind + V-ing?", m: "bạn có phiền ... không?", use: "nhờ vả rất lịch sự", ex: "Would you mind opening the window?" },
    { c: "Can I have ..., please?", m: "cho tôi ... nhé", use: "xin/gọi thứ gì đó", ex: "Can I have the menu, please?" },
    { c: "Is it OK if I ...?", m: "tôi ... có được không?", use: "xin phép làm gì đó", ex: "Is it OK if I sit here?" },
    { c: "Can you do me a favor?", m: "giúp mình một việc được không?", use: "mở đầu trước khi nhờ việc", ex: "Can you do me a favor? Watch my bag a minute." },
    { c: "After you", m: "mời bạn trước", use: "nhường đường/nhường lượt lịch thiệp", ex: "(At the door) After you! — Oh, thank you!" },
    { c: "That's very kind of you", m: "bạn tốt quá", use: "cảm ơn khi được giúp", ex: "I carried it for her. — That's very kind of you!" },
    { c: "Sorry to bother you", m: "xin lỗi làm phiền bạn", use: "mở đầu khi phải làm phiền ai", ex: "Sorry to bother you, but the wifi isn't working." },
    { c: "No problem", m: "không vấn đề gì", use: "đáp lại lời cảm ơn/xin lỗi", ex: "Thanks a lot! — No problem!" },
  ],
  phrases: [
    { en: "Could I ask you something?", vi: "Mình hỏi bạn chút được không?" },
    { en: "Would you like some help?", vi: "Bạn có cần giúp không?" },
    { en: "Thank you so much, I owe you one.", vi: "Cảm ơn nhiều lắm, mình nợ bạn một lần." },
    { en: "It's my pleasure.", vi: "Rất hân hạnh được giúp." },
    { en: "Don't mention it.", vi: "Có gì đâu mà." },
    { en: "Anytime!", vi: "Lúc nào cần cứ gọi!" },
  ],
  dialogue: [
    { who: "A", en: "Excuse me, sorry to bother you. Could you help me, please?", vi: "Xin lỗi làm phiền bạn. Bạn giúp mình được không?" },
    { who: "B", en: "Of course! What do you need?", vi: "Tất nhiên rồi! Bạn cần gì?" },
    { who: "A", en: "Would you mind taking a photo of us?", vi: "Bạn có phiền chụp giúp bọn mình tấm ảnh không?" },
    { who: "B", en: "Not at all! Say cheese... Done!", vi: "Không hề! Cười lên nào... Xong rồi!" },
    { who: "A", en: "That's very kind of you. Thank you so much!", vi: "Bạn tốt quá. Cảm ơn nhiều nhé!" },
    { who: "B", en: "No problem. Have a great trip!", vi: "Không có gì. Chúc chuyến đi vui vẻ!" },
  ],
},
{
  id: "reactions", icon: "⚡", level: 2,
  name: "Thực chiến: Phản xạ đáp lời",
  nameEn: "Quick Reactions",
  vocab: [
    { w: "amazing", ipa: "/əˈmeɪzɪŋ/", m: "tuyệt vời, kinh ngạc", ex: "That's amazing news!" },
    { w: "terrible", ipa: "/ˈterəbl/", m: "tệ hại", ex: "The traffic was terrible today." },
    { w: "seriously", ipa: "/ˈsɪriəsli/", m: "nghiêm túc đấy", ex: "Seriously? You won the lottery?" },
    { w: "pity", ipa: "/ˈpɪti/", m: "điều đáng tiếc", ex: "What a pity you can't come!" },
    { w: "joking", ipa: "/ˈdʒoʊkɪŋ/", m: "nói đùa", ex: "You're joking, right?" },
    { w: "unbelievable", ipa: "/ˌʌnbɪˈliːvəbl/", m: "khó tin", ex: "Unbelievable! We won again!" },
  ],
  chunks: [
    { c: "That sounds great!", m: "nghe tuyệt đấy!", use: "phản ứng tích cực với đề xuất", ex: "Beach trip on Sunday? — That sounds great!" },
    { c: "Really?", m: "thật á?", use: "thể hiện ngạc nhiên + muốn nghe tiếp", ex: "I'm moving to Japan. — Really? When?" },
    { c: "No way!", m: "không thể nào!", use: "ngạc nhiên mạnh (thân mật)", ex: "She's only 40? No way!" },
    { c: "What a pity!", m: "tiếc quá!", use: "tiếc nuối cho chuyện không may nhỏ", ex: "The show is sold out. — What a pity!" },
    { c: "Congratulations!", m: "chúc mừng!", use: "khi ai đó có tin vui", ex: "I got the job! — Congratulations!" },
    { c: "Good luck!", m: "chúc may mắn!", use: "trước kỳ thi/phỏng vấn/thử thách", ex: "My exam is tomorrow. — Good luck!" },
    { c: "I'm glad to hear that", m: "mừng khi nghe vậy", use: "phản hồi tin tốt một cách ấm áp", ex: "Mom is much better now. — I'm glad to hear that." },
    { c: "That's too bad", m: "tệ thật, tiếc thật", use: "chia buồn chuyện không may", ex: "Our picnic is cancelled. — That's too bad." },
    { c: "You must be joking!", m: "bạn đùa chắc!", use: "không tin nổi điều vừa nghe", ex: "He ate 10 bowls of pho! — You must be joking!" },
    { c: "Sounds like a plan!", m: "chốt vậy đi!", use: "đồng ý với kế hoạch", ex: "Coffee at 3, cinema at 5? — Sounds like a plan!" },
  ],
  phrases: [
    { en: "That's wonderful news!", vi: "Tin tuyệt vời quá!" },
    { en: "I'm so sorry to hear that.", vi: "Mình rất tiếc khi nghe điều đó." },
    { en: "Wow, tell me more!", vi: "Ồ, kể thêm đi!" },
    { en: "That happens to everyone.", vi: "Chuyện đó ai cũng gặp mà." },
    { en: "Better luck next time!", vi: "Lần sau may mắn hơn nhé!" },
    { en: "Well done!", vi: "Làm tốt lắm!" },
  ],
  dialogue: [
    { who: "A", en: "Guess what? I passed the IELTS exam with a 7.0!", vi: "Đoán xem? Mình thi IELTS được 7.0 rồi!" },
    { who: "B", en: "No way! Congratulations! I'm so glad to hear that!", vi: "Không thể nào! Chúc mừng nhé! Mừng cho bạn quá!" },
    { who: "A", en: "Thanks! But my friend Minh didn't pass this time.", vi: "Cảm ơn! Nhưng Minh bạn mình lần này chưa qua." },
    { who: "B", en: "Oh, that's too bad. Tell him better luck next time.", vi: "Ồ, tiếc thật. Nhắn cậu ấy lần sau may mắn hơn nhé." },
    { who: "A", en: "I will. Hey, let's celebrate this weekend!", vi: "Ừ mình sẽ nhắn. Này, cuối tuần ăn mừng đi!" },
    { who: "B", en: "That sounds great! Sounds like a plan!", vi: "Nghe tuyệt đấy! Chốt vậy đi!" },
  ],
},
{
  id: "opinions", icon: "💭", level: 2,
  name: "Thực chiến: Nêu & hỏi ý kiến",
  nameEn: "Giving Opinions",
  vocab: [
    { w: "opinion", ipa: "/əˈpɪnjən/", m: "ý kiến", ex: "Everyone has a different opinion." },
    { w: "honest", ipa: "/ˈɑːnɪst/", m: "thành thật", ex: "Give me your honest opinion." },
    { w: "depend", ipa: "/dɪˈpend/", m: "tùy thuộc", ex: "It depends on the weather." },
    { w: "point", ipa: "/pɔɪnt/", m: "quan điểm, ý", ex: "I see your point." },
    { w: "prefer", ipa: "/prɪˈfɜːr/", m: "thích hơn", ex: "I prefer tea to coffee." },
    { w: "suggest", ipa: "/səˈdʒest/", m: "đề xuất", ex: "What do you suggest?" },
  ],
  chunks: [
    { c: "What do you think?", m: "bạn nghĩ sao?", use: "hỏi ý kiến trực tiếp", ex: "New haircut. What do you think?" },
    { c: "In my opinion, ...", m: "theo ý mình thì ...", use: "mở đầu khi nêu quan điểm", ex: "In my opinion, this plan is too risky." },
    { c: "To be honest, ...", m: "thành thật mà nói ...", use: "trước khi nói thẳng suy nghĩ", ex: "To be honest, I don't like that color." },
    { c: "I see your point, but ...", m: "mình hiểu ý bạn, nhưng ...", use: "phản đối một cách tôn trọng", ex: "I see your point, but we don't have the budget." },
    { c: "That makes sense", m: "nghe hợp lý đấy", use: "công nhận lập luận của người khác", ex: "We should leave early to avoid traffic. — That makes sense." },
    { c: "I'm not sure about that", m: "mình không chắc về điều đó", use: "nghi ngờ nhẹ nhàng, không gay gắt", ex: "This phone is the best! — Hmm, I'm not sure about that." },
    { c: "It depends", m: "còn tùy", use: "khi câu trả lời không cố định", ex: "Do you like karaoke? — It depends on the songs!" },
    { c: "If you ask me, ...", m: "nếu hỏi mình thì ...", use: "nêu ý kiến cá nhân (thân mật)", ex: "If you ask me, the old menu was better." },
    { c: "Absolutely!", m: "chuẩn luôn!", use: "đồng ý 100%", ex: "Vietnamese coffee is the best! — Absolutely!" },
    { c: "Not really", m: "cũng không hẳn", use: "phủ định nhẹ, lịch sự", ex: "Do you like horror films? — Not really." },
  ],
  phrases: [
    { en: "How do you feel about it?", vi: "Bạn thấy chuyện đó thế nào?" },
    { en: "I totally agree with you.", vi: "Mình hoàn toàn đồng ý với bạn." },
    { en: "I'm afraid I disagree.", vi: "E là mình không đồng ý." },
    { en: "That's a good idea, but there's a problem.", vi: "Ý hay đấy, nhưng có một vấn đề." },
    { en: "Which one do you prefer?", vi: "Bạn thích cái nào hơn?" },
    { en: "Let's hear both sides.", vi: "Nghe cả hai phía xem sao." },
  ],
  dialogue: [
    { who: "A", en: "Should we travel to Da Lat or Phu Quoc this summer? What do you think?", vi: "Hè này đi Đà Lạt hay Phú Quốc nhỉ? Bạn nghĩ sao?" },
    { who: "B", en: "To be honest, I prefer Da Lat. It's cooler and cheaper.", vi: "Thành thật mà nói mình thích Đà Lạt hơn. Mát hơn và rẻ hơn." },
    { who: "A", en: "I see your point, but Phu Quoc has the beach!", vi: "Mình hiểu ý bạn, nhưng Phú Quốc có biển!" },
    { who: "B", en: "That makes sense. It depends on what we want: relaxing or swimming.", vi: "Cũng hợp lý. Còn tùy mình muốn gì: nghỉ dưỡng hay tắm biển." },
    { who: "A", en: "If you ask me, we work too much — we need the beach!", vi: "Nếu hỏi mình thì bọn mình làm việc nhiều quá rồi — cần biển!" },
    { who: "B", en: "Absolutely! Phu Quoc it is!", vi: "Chuẩn luôn! Chốt Phú Quốc!" },
  ],
},
{
  id: "conversation-flow", icon: "🔄", level: 3,
  name: "Thực chiến: Giữ nhịp hội thoại",
  nameEn: "Keeping the Conversation Going",
  vocab: [
    { w: "anyway", ipa: "/ˈeniweɪ/", m: "dù sao thì, mà thôi", ex: "Anyway, let's talk about the trip." },
    { w: "remind", ipa: "/rɪˈmaɪnd/", m: "gợi nhớ, nhắc", ex: "That reminds me of my hometown." },
    { w: "interrupt", ipa: "/ˌɪntəˈrʌpt/", m: "ngắt lời", ex: "Sorry to interrupt, but it's late." },
    { w: "topic", ipa: "/ˈtɑːpɪk/", m: "chủ đề", ex: "Let's change the topic." },
    { w: "actually", ipa: "/ˈæktʃuəli/", m: "thật ra", ex: "Actually, I have a different idea." },
    { w: "exactly", ipa: "/ɪɡˈzæktli/", m: "chính xác", ex: "That's exactly what I mean!" },
  ],
  chunks: [
    { c: "By the way, ...", m: "nhân tiện, ...", use: "chuyển sang chuyện khác một cách tự nhiên", ex: "By the way, did you call your mom?" },
    { c: "Anyway, ...", m: "mà thôi, quay lại chuyện chính ...", use: "kéo câu chuyện về chủ đề chính", ex: "Anyway, what time is the meeting?" },
    { c: "You know what?", m: "biết gì không?", use: "gây chú ý trước khi nói điều thú vị", ex: "You know what? Let's just order pizza." },
    { c: "Let me think ...", m: "để mình nghĩ đã ...", use: "câu giờ khi cần suy nghĩ — đừng im lặng!", ex: "Best restaurant here? Let me think..." },
    { c: "How should I put it ...", m: "nói thế nào nhỉ ...", use: "câu giờ khi khó diễn đạt", ex: "The movie was... how should I put it... strange." },
    { c: "That reminds me of ...", m: "chuyện đó làm mình nhớ tới ...", use: "nối sang câu chuyện liên quan", ex: "That reminds me of our trip to Hue!" },
    { c: "Speaking of ...", m: "nhắc mới nhớ, nói về ...", use: "bắt cầu từ từ khóa vừa nhắc", ex: "Speaking of food, I'm starving!" },
    { c: "Where was I?", m: "mình kể đến đâu rồi nhỉ?", use: "quay lại mạch chuyện sau khi bị ngắt", ex: "Sorry, phone call... Where was I?" },
    { c: "Long story short, ...", m: "nói ngắn gọn là ...", use: "tóm tắt câu chuyện dài", ex: "Long story short, we missed the flight." },
    { c: "It's been great talking to you", m: "trò chuyện với bạn vui thật", use: "kết thúc hội thoại đẹp", ex: "It's been great talking to you. Let's keep in touch!" },
  ],
  phrases: [
    { en: "Sorry to interrupt, but I have a question.", vi: "Xin lỗi ngắt lời, nhưng mình có câu hỏi." },
    { en: "Go on, I'm listening.", vi: "Nói tiếp đi, mình đang nghe." },
    { en: "And then what happened?", vi: "Rồi sau đó thế nào?" },
    { en: "That's an interesting story.", vi: "Chuyện thú vị đấy." },
    { en: "We should talk more often.", vi: "Bọn mình nên trò chuyện thường xuyên hơn." },
    { en: "I'll let you go now.", vi: "Thôi mình không giữ bạn nữa." },
  ],
  dialogue: [
    { who: "A", en: "So the fish was THIS big... oh, hold on, my phone... OK, where was I?", vi: "Con cá nó to CỠ NÀY... ơ khoan, điện thoại... Rồi, mình kể đến đâu rồi nhỉ?" },
    { who: "B", en: "The big fish! Go on, I'm listening.", vi: "Con cá to! Kể tiếp đi, mình đang nghe." },
    { who: "A", en: "Right! Long story short, the fish escaped with my hat.", vi: "À đúng! Nói ngắn gọn là con cá xổng mất cùng cái mũ của mình." },
    { who: "B", en: "You must be joking! By the way, speaking of fishing — are you free this Sunday?", vi: "Bạn đùa chắc! Nhân tiện, nhắc chuyện câu cá — chủ nhật này rảnh không?" },
    { who: "A", en: "Let me think... yes! You know what? This time, you hold the hats.", vi: "Để mình nghĩ đã... rảnh! Biết gì không? Lần này bạn giữ mũ nhé." },
    { who: "B", en: "Deal! It's been great talking to you, as always.", vi: "Chốt! Nói chuyện với bạn lúc nào cũng vui thật." },
  ],
}
);

// ===== HỢP NHẤT DỮ LIỆU MỞ RỘNG VÀO TOPICS =====
TOPICS.forEach(t => {
  if (!t.chunks) t.chunks = [];
  if (CHUNKS[t.id]) t.chunks = t.chunks.concat(CHUNKS[t.id]);
  if (EXTRA_VOCAB[t.id]) t.vocab = t.vocab.concat(EXTRA_VOCAB[t.id]);
  if (EXTRA_PHRASES[t.id]) t.phrases = t.phrases.concat(EXTRA_PHRASES[t.id]);
});
