// ============================================================
// EnglishDaily — DỮ LIỆU MỞ RỘNG ĐỢT 2 (nạp sau data2.js)
// 1) 6 chủ đề thực chiến MỚI (đầy đủ vocab + chunks + phrases + dialogue)
// 2) CANDO: câu "học xong bạn làm được gì" cho từng chủ đề (hiện trên bài học)
// ============================================================

const NEW_TOPICS = [
{
  id: "making-friends", icon: "🤝", level: 1,
  name: "Làm quen & Kết bạn",
  nameEn: "Making Friends",
  vocab: [
    { w: "hang out", ipa: "/hæŋ aʊt/", m: "đi chơi, tụ tập", ex: "Do you want to hang out this weekend?" },
    { w: "get to know", ipa: "/ɡet tə noʊ/", m: "làm quen, tìm hiểu", ex: "I'd love to get to know you better." },
    { w: "in common", ipa: "/ɪn ˈkɑːmən/", m: "điểm chung", ex: "We have a lot in common." },
    { w: "close friend", ipa: "/kloʊs frend/", m: "bạn thân", ex: "She's a close friend of mine." },
    { w: "introduce", ipa: "/ˌɪntrəˈduːs/", m: "giới thiệu", ex: "Let me introduce you to my friend." },
    { w: "get along", ipa: "/ɡet əˈlɔːŋ/", m: "hợp nhau, hòa thuận", ex: "We get along really well." },
    { w: "keep in touch", ipa: "/kiːp ɪn tʌtʃ/", m: "giữ liên lạc", ex: "Let's keep in touch after the trip." },
  ],
  chunks: [
    { c: "Is this seat taken?", m: "chỗ này có ai ngồi chưa?", use: "bắt chuyện ở quán/lớp/sự kiện", ex: "Is this seat taken? — No, go ahead!" },
    { c: "Do you come here often?", m: "bạn hay đến đây không?", use: "câu mở chuyện với người mới gặp", ex: "Do you come here often? — Yeah, every weekend." },
    { c: "What do you do?", m: "bạn làm nghề gì?", use: "hỏi nghề nghiệp khi mới quen", ex: "So, what do you do? — I'm a teacher." },
    { c: "We should hang out sometime", m: "bữa nào đi chơi nhé", use: "ngỏ ý muốn gặp lại", ex: "We should hang out sometime! — Sure, I'd like that." },
    { c: "Can I get your number?", m: "cho mình xin số nhé?", use: "xin liên lạc lịch sự", ex: "Can I get your number? Let's stay in touch." },
    { c: "It was nice meeting you", m: "rất vui được gặp bạn", use: "chào tạm biệt người mới quen", ex: "It was nice meeting you! — You too!" },
    { c: "What are you into?", m: "bạn thích/mê cái gì?", use: "hỏi sở thích để tìm điểm chung", ex: "What are you into? — Mostly music and hiking." },
  ],
  phrases: [
    { en: "Hi, I don't think we've met. I'm Duong.", vi: "Chào, hình như mình chưa gặp nhau. Mình là Dương." },
    { en: "How do you know the host?", vi: "Bạn quen chủ tiệc thế nào?" },
    { en: "I like your style!", vi: "Mình thích phong cách của bạn đấy!" },
    { en: "Mind if I join you?", vi: "Mình ngồi cùng được không?" },
    { en: "We have so much in common!", vi: "Bọn mình có nhiều điểm chung ghê!" },
    { en: "Let's grab lunch sometime.", vi: "Bữa nào đi ăn trưa nhé." },
  ],
  dialogue: [
    { who: "A", en: "Hi! Is this seat taken?", vi: "Chào! Chỗ này có ai ngồi chưa?" },
    { who: "B", en: "No, go ahead! Are you here for the English club too?", vi: "Chưa, mời ngồi! Bạn cũng đến câu lạc bộ tiếng Anh à?" },
    { who: "A", en: "Yeah, it's my first time. I'm Duong, by the way.", vi: "Ừ, lần đầu mình đến. Nhân tiện, mình là Dương." },
    { who: "B", en: "Nice to meet you, Duong! I'm Lan. What are you into?", vi: "Rất vui được gặp Dương! Mình là Lan. Bạn thích gì nào?" },
    { who: "A", en: "Music, mostly. And you? We might have a lot in common!", vi: "Chủ yếu là âm nhạc. Còn bạn? Biết đâu bọn mình nhiều điểm chung!" },
    { who: "B", en: "Same here! We should hang out sometime. Can I get your number?", vi: "Mình cũng vậy! Bữa nào đi chơi nhé. Cho mình xin số được không?" },
  ],
},
{
  id: "coffee-shop", icon: "🧋", level: 1,
  name: "Quán cà phê & Đồ uống",
  nameEn: "At the Coffee Shop",
  vocab: [
    { w: "order", ipa: "/ˈɔːrdər/", m: "gọi (đồ uống)", ex: "Can I order a coffee, please?" },
    { w: "size", ipa: "/saɪz/", m: "cỡ (ly)", ex: "What size would you like?" },
    { w: "iced", ipa: "/aɪst/", m: "đá, ướp lạnh", ex: "One iced tea, please." },
    { w: "takeaway", ipa: "/ˈteɪkəweɪ/", m: "mang đi", ex: "Is this for takeaway?" },
    { w: "straw", ipa: "/strɔː/", m: "ống hút", ex: "Can I have a straw?" },
    { w: "refill", ipa: "/ˈriːfɪl/", m: "châm/rót thêm miễn phí", ex: "Is the refill free?" },
    { w: "topping", ipa: "/ˈtɑːpɪŋ/", m: "topping, phần thêm", ex: "Would you like any toppings?" },
  ],
  chunks: [
    { c: "Can I get a ...?", m: "cho mình một ... nhé?", use: "gọi đồ uống tự nhiên", ex: "Can I get a large iced latte?" },
    { c: "For here or takeaway?", m: "uống tại chỗ hay mang đi?", use: "câu nhân viên luôn hỏi", ex: "For here or takeaway? — Takeaway, please." },
    { c: "Less ice, please", m: "cho ít đá thôi nhé", use: "yêu cầu riêng phổ biến", ex: "One iced coffee, less ice, please." },
    { c: "Not too sweet", m: "đừng ngọt quá", use: "điều chỉnh độ ngọt", ex: "Can you make it not too sweet?" },
    { c: "What do you recommend?", m: "bạn gợi ý món nào?", use: "khi chưa biết chọn gì", ex: "First time here — what do you recommend?" },
    { c: "Keep the change", m: "khỏi thối lại", use: "boa nhẹ khi trả tiền mặt", ex: "Here's fifty. Keep the change!" },
    { c: "Is there wifi here?", m: "ở đây có wifi không?", use: "hỏi tiện ích khi ngồi làm việc", ex: "Is there wifi here? — Yes, the password is on the wall." },
  ],
  phrases: [
    { en: "A cappuccino, please.", vi: "Cho mình một ly cappuccino." },
    { en: "Can I have oat milk instead?", vi: "Cho mình đổi sang sữa yến mạch được không?" },
    { en: "How much is a medium?", vi: "Cỡ vừa bao nhiêu tiền?" },
    { en: "Can I pay by card?", vi: "Trả bằng thẻ được không?" },
    { en: "Where can I sit?", vi: "Mình ngồi đâu được nhỉ?" },
    { en: "This tastes great!", vi: "Uống ngon thật!" },
  ],
  dialogue: [
    { who: "A", en: "Hi! What can I get for you?", vi: "Chào bạn! Bạn dùng gì ạ?" },
    { who: "B", en: "Can I get a large iced latte, less ice, please?", vi: "Cho mình một ly latte đá cỡ lớn, ít đá nhé?" },
    { who: "A", en: "Sure! For here or takeaway?", vi: "Vâng ạ! Uống tại chỗ hay mang đi?" },
    { who: "B", en: "For here. What do you recommend for a snack?", vi: "Tại chỗ. Bạn gợi ý món ăn nhẹ nào ngon không?" },
    { who: "A", en: "Our almond croissant is very popular. Anything else?", vi: "Bánh sừng bò hạnh nhân bên mình rất được thích. Còn gì nữa không ạ?" },
    { who: "B", en: "That's all, thanks. Is there wifi here?", vi: "Vậy thôi, cảm ơn. Ở đây có wifi không?" },
  ],
},
{
  id: "online-order", icon: "📦", level: 2,
  name: "Mua hàng online & Giao nhận",
  nameEn: "Online Shopping & Delivery",
  vocab: [
    { w: "order", ipa: "/ˈɔːrdər/", m: "đơn hàng; đặt hàng", ex: "My order hasn't arrived yet." },
    { w: "delivery", ipa: "/dɪˈlɪvəri/", m: "giao hàng", ex: "Delivery takes three days." },
    { w: "track", ipa: "/træk/", m: "theo dõi (đơn)", ex: "You can track your order online." },
    { w: "refund", ipa: "/ˈriːfʌnd/", m: "hoàn tiền", ex: "I'd like a refund for this item." },
    { w: "return", ipa: "/rɪˈtɜːrn/", m: "trả hàng", ex: "Can I return this if it doesn't fit?" },
    { w: "shipping fee", ipa: "/ˈʃɪpɪŋ fiː/", m: "phí vận chuyển", ex: "Is the shipping fee free?" },
    { w: "in stock", ipa: "/ɪn stɑːk/", m: "còn hàng", ex: "Is this item still in stock?" },
  ],
  chunks: [
    { c: "When will it arrive?", m: "khi nào hàng tới?", use: "hỏi thời gian giao hàng", ex: "I ordered yesterday. When will it arrive?" },
    { c: "My order hasn't arrived", m: "đơn của tôi chưa tới", use: "khiếu nại giao hàng trễ", ex: "It's been a week. My order hasn't arrived." },
    { c: "It came damaged", m: "hàng đến bị hỏng", use: "báo hàng lỗi để đổi/trả", ex: "The cup came damaged. Can I get a replacement?" },
    { c: "I'd like to return this", m: "tôi muốn trả món này", use: "yêu cầu trả hàng", ex: "I'd like to return this — it's the wrong size." },
    { c: "Can I get a refund?", m: "tôi được hoàn tiền chứ?", use: "yêu cầu hoàn tiền", ex: "It's broken. Can I get a refund?" },
    { c: "Is cash on delivery available?", m: "có thanh toán khi nhận hàng không?", use: "hỏi hình thức COD", ex: "Is cash on delivery available? — Yes, it is." },
    { c: "Leave it at the door", m: "cứ để trước cửa giúp mình", use: "dặn shipper khi vắng nhà", ex: "I'm busy — just leave it at the door, please." },
  ],
  phrases: [
    { en: "Do you deliver to this address?", vi: "Bên bạn giao tới địa chỉ này không?" },
    { en: "Can I change my delivery address?", vi: "Mình đổi địa chỉ giao được không?" },
    { en: "The item is different from the picture.", vi: "Món hàng khác với hình." },
    { en: "How long is the warranty?", vi: "Bảo hành bao lâu?" },
    { en: "I'd like to cancel my order.", vi: "Mình muốn hủy đơn." },
    { en: "Please call me before you arrive.", vi: "Gọi mình trước khi tới nhé." },
  ],
  dialogue: [
    { who: "A", en: "Hello, I'm calling about my order. It hasn't arrived yet.", vi: "Alô, tôi gọi hỏi về đơn hàng. Nó vẫn chưa tới." },
    { who: "B", en: "I'm sorry. Could you give me your order number?", vi: "Tôi xin lỗi. Anh cho tôi mã đơn hàng được không?" },
    { who: "A", en: "Sure, it's 4471. I ordered five days ago.", vi: "Được, mã 4471. Tôi đặt năm ngày trước rồi." },
    { who: "B", en: "Let me check... It's out for delivery today.", vi: "Để tôi kiểm tra... Đơn đang được giao trong hôm nay ạ." },
    { who: "A", en: "Great. If I'm not home, can you leave it at the door?", vi: "Tốt quá. Nếu tôi không có nhà, để trước cửa giúp nhé?" },
    { who: "B", en: "Of course. The driver will call you before arriving.", vi: "Được ạ. Tài xế sẽ gọi trước khi tới." },
  ],
},
{
  id: "describing-people", icon: "🧑", level: 2,
  name: "Mô tả người",
  nameEn: "Describing People",
  vocab: [
    { w: "tall", ipa: "/tɔːl/", m: "cao", ex: "He's tall and slim." },
    { w: "curly hair", ipa: "/ˈkɜːrli her/", m: "tóc xoăn", ex: "She has long curly hair." },
    { w: "friendly", ipa: "/ˈfrendli/", m: "thân thiện", ex: "My new colleague is very friendly." },
    { w: "polite", ipa: "/pəˈlaɪt/", m: "lịch sự", ex: "He's always polite to everyone." },
    { w: "middle-aged", ipa: "/ˌmɪdl ˈeɪdʒd/", m: "trung niên", ex: "A middle-aged man asked for directions." },
    { w: "generous", ipa: "/ˈdʒenərəs/", m: "hào phóng", ex: "She's generous and kind." },
    { w: "shy", ipa: "/ʃaɪ/", m: "nhút nhát", ex: "He was shy as a child." },
  ],
  chunks: [
    { c: "What does he look like?", m: "anh ấy trông thế nào?", use: "hỏi ngoại hình một người", ex: "What does he look like? — Tall, with glasses." },
    { c: "What's she like?", m: "cô ấy tính tình ra sao?", use: "hỏi tính cách (khác với ngoại hình)", ex: "What's she like? — Very kind and funny." },
    { c: "He looks like ...", m: "anh ấy trông giống ...", use: "so sánh ngoại hình", ex: "He looks like a movie star!" },
    { c: "in his thirties", m: "khoảng ngoài 30 tuổi", use: "ước lượng độ tuổi", ex: "She's probably in her thirties." },
    { c: "the one with ...", m: "người mà có ...", use: "chỉ ra một người trong nhóm", ex: "That's my sister — the one with glasses." },
    { c: "a good sense of humor", m: "khiếu hài hước", use: "khen tính cách", ex: "He has a good sense of humor." },
    { c: "down to earth", m: "giản dị, thực tế", use: "khen người dễ gần", ex: "The boss is rich but very down to earth." },
  ],
  phrases: [
    { en: "She has beautiful brown eyes.", vi: "Cô ấy có đôi mắt nâu đẹp." },
    { en: "He's a bit taller than me.", vi: "Anh ấy cao hơn mình một chút." },
    { en: "Everyone likes her because she's so kind.", vi: "Ai cũng quý cô ấy vì cô ấy tốt bụng." },
    { en: "He's wearing a blue shirt.", vi: "Anh ấy mặc áo sơ mi xanh." },
    { en: "My best friend is really outgoing.", vi: "Bạn thân mình rất hướng ngoại." },
    { en: "Can you describe him for me?", vi: "Bạn tả anh ấy giúp mình được không?" },
  ],
  dialogue: [
    { who: "A", en: "I'll meet your brother at the station. What does he look like?", vi: "Mình sẽ đón anh bạn ở ga. Anh ấy trông thế nào?" },
    { who: "B", en: "He's tall, in his twenties, with short curly hair.", vi: "Anh ấy cao, khoảng ngoài 20, tóc xoăn ngắn." },
    { who: "A", en: "Okay. Anything else? The station will be crowded.", vi: "Được. Còn gì nữa không? Ga sẽ đông lắm." },
    { who: "B", en: "He'll be wearing glasses and a red backpack.", vi: "Anh ấy đeo kính và mang ba lô đỏ." },
    { who: "A", en: "Great. And what's he like? Is he chatty?", vi: "Tốt. Anh ấy tính sao? Có nói nhiều không?" },
    { who: "B", en: "A little shy at first, but very friendly once you know him.", vi: "Lúc đầu hơi nhút nhát, nhưng thân quen rồi thì rất dễ mến." },
  ],
},
{
  id: "renting", icon: "🔑", level: 2,
  name: "Thuê nhà & Phòng trọ",
  nameEn: "Renting a Place",
  vocab: [
    { w: "rent", ipa: "/rent/", m: "tiền thuê; thuê", ex: "How much is the rent per month?" },
    { w: "deposit", ipa: "/dɪˈpɑːzɪt/", m: "tiền đặt cọc", ex: "You need to pay one month's deposit." },
    { w: "landlord", ipa: "/ˈlændlɔːrd/", m: "chủ nhà", ex: "The landlord lives next door." },
    { w: "furnished", ipa: "/ˈfɜːrnɪʃt/", m: "có sẵn nội thất", ex: "Is the room furnished?" },
    { w: "utilities", ipa: "/juːˈtɪlətiz/", m: "điện nước, tiện ích", ex: "Are utilities included in the rent?" },
    { w: "contract", ipa: "/ˈkɑːntrækt/", m: "hợp đồng", ex: "Please read the contract carefully." },
    { w: "move in", ipa: "/muːv ɪn/", m: "dọn vào ở", ex: "When can I move in?" },
  ],
  chunks: [
    { c: "Is it still available?", m: "phòng còn trống không?", use: "hỏi khi liên hệ thuê", ex: "I saw your ad — is it still available?" },
    { c: "How much is the rent?", m: "tiền thuê bao nhiêu?", use: "hỏi giá thuê", ex: "How much is the rent per month?" },
    { c: "Are utilities included?", m: "đã gồm điện nước chưa?", use: "hỏi chi phí kèm theo", ex: "Are utilities included, or do I pay separately?" },
    { c: "Can I have a look?", m: "mình xem phòng được không?", use: "xin đi xem nhà", ex: "Can I have a look this afternoon?" },
    { c: "Is there a deposit?", m: "có phải đặt cọc không?", use: "hỏi về tiền cọc", ex: "Is there a deposit? — Yes, one month." },
    { c: "When can I move in?", m: "khi nào mình dọn vào được?", use: "chốt ngày nhận phòng", ex: "Great, I'll take it. When can I move in?" },
    { c: "Is it close to ...?", m: "có gần ... không?", use: "hỏi vị trí", ex: "Is it close to the bus stop?" },
  ],
  phrases: [
    { en: "I'm looking for a room to rent.", vi: "Mình đang tìm phòng để thuê." },
    { en: "Does the room get much sunlight?", vi: "Phòng có nhiều nắng không?" },
    { en: "Can I pay the rent monthly?", vi: "Mình trả tiền thuê theo tháng được chứ?" },
    { en: "Is the neighborhood safe and quiet?", vi: "Khu này có an toàn và yên tĩnh không?" },
    { en: "How long is the contract?", vi: "Hợp đồng thuê bao lâu?" },
    { en: "The kitchen is a bit small.", vi: "Nhà bếp hơi nhỏ." },
  ],
  dialogue: [
    { who: "A", en: "Hello, I'm calling about the room for rent. Is it still available?", vi: "Alô, tôi gọi hỏi về phòng cho thuê. Phòng còn trống không ạ?" },
    { who: "B", en: "Yes, it is! It's a furnished room with a private bathroom.", vi: "Còn ạ! Phòng có sẵn nội thất và toilet riêng." },
    { who: "A", en: "Sounds good. How much is the rent, and are utilities included?", vi: "Nghe được đấy. Tiền thuê bao nhiêu, và đã gồm điện nước chưa ạ?" },
    { who: "B", en: "Three million a month. Water is included; electricity is separate.", vi: "Ba triệu một tháng. Nước bao gồm; điện tính riêng." },
    { who: "A", en: "Can I have a look tomorrow afternoon?", vi: "Chiều mai tôi xem phòng được không?" },
    { who: "B", en: "Of course. If you like it, you can move in this weekend.", vi: "Được chứ. Nếu ưng, cuối tuần này anh dọn vào được luôn." },
  ],
},
{
  id: "job-interview", icon: "📋", level: 3,
  name: "Phỏng vấn xin việc",
  nameEn: "Job Interview",
  vocab: [
    { w: "experience", ipa: "/ɪkˈspɪriəns/", m: "kinh nghiệm", ex: "I have three years of experience." },
    { w: "strength", ipa: "/streŋθ/", m: "điểm mạnh", ex: "My greatest strength is teamwork." },
    { w: "weakness", ipa: "/ˈwiːknəs/", m: "điểm yếu", ex: "I'm working on my weaknesses." },
    { w: "position", ipa: "/pəˈzɪʃn/", m: "vị trí (công việc)", ex: "I'm applying for the sales position." },
    { w: "responsible for", ipa: "/rɪˈspɑːnsəbl fɔːr/", m: "chịu trách nhiệm về", ex: "I was responsible for the team's budget." },
    { w: "available", ipa: "/əˈveɪləbl/", m: "sẵn sàng, có thể", ex: "I'm available to start next month." },
    { w: "salary", ipa: "/ˈsæləri/", m: "lương", ex: "What is the salary range?" },
  ],
  chunks: [
    { c: "Tell me about yourself", m: "hãy giới thiệu về bản thân", use: "câu mở đầu mọi buổi phỏng vấn", ex: "Tell me about yourself. — Sure, I'm a marketing graduate..." },
    { c: "Why do you want this job?", m: "vì sao bạn muốn công việc này?", use: "câu hỏi kinh điển", ex: "Why do you want this job? — I admire your company's mission." },
    { c: "I have experience in ...", m: "tôi có kinh nghiệm về ...", use: "nêu thế mạnh chuyên môn", ex: "I have experience in customer service." },
    { c: "I'm a quick learner", m: "tôi học việc nhanh", use: "khẳng định khả năng thích nghi", ex: "I'm new to this field, but I'm a quick learner." },
    { c: "I work well under pressure", m: "tôi làm tốt dưới áp lực", use: "trả lời câu hỏi về áp lực", ex: "I stay calm — I work well under pressure." },
    { c: "Do you have any questions for us?", m: "bạn có câu hỏi nào cho chúng tôi không?", use: "câu cuối buổi phỏng vấn", ex: "Do you have any questions for us? — Yes, about the team structure." },
    { c: "When can you start?", m: "khi nào bạn có thể bắt đầu?", use: "dấu hiệu phỏng vấn thuận lợi", ex: "When can you start? — I'm available immediately." },
  ],
  phrases: [
    { en: "Thank you for this opportunity.", vi: "Cảm ơn vì cơ hội này." },
    { en: "I'm very interested in this role.", vi: "Tôi rất hứng thú với vị trí này." },
    { en: "In my previous job, I led a small team.", vi: "Ở công việc trước, tôi dẫn dắt một nhóm nhỏ." },
    { en: "I'd describe myself as hardworking and reliable.", vi: "Tôi tự nhận mình chăm chỉ và đáng tin cậy." },
    { en: "Could you tell me more about the role?", vi: "Anh/chị nói thêm về vị trí này được không?" },
    { en: "I look forward to hearing from you.", vi: "Tôi mong sớm nhận phản hồi từ anh/chị." },
  ],
  dialogue: [
    { who: "A", en: "Good morning! Thanks for coming in. Tell me about yourself.", vi: "Chào buổi sáng! Cảm ơn bạn đã đến. Hãy giới thiệu về bản thân." },
    { who: "B", en: "Thank you. I'm a marketing graduate with two years of experience.", vi: "Cảm ơn ạ. Tôi tốt nghiệp ngành marketing, có hai năm kinh nghiệm." },
    { who: "A", en: "Great. Why do you want to work here?", vi: "Tốt. Vì sao bạn muốn làm việc ở đây?" },
    { who: "B", en: "I admire your products, and I'm a quick learner who works well in a team.", vi: "Tôi ngưỡng mộ sản phẩm của công ty, và tôi học nhanh, làm việc nhóm tốt." },
    { who: "A", en: "Good to hear. When can you start?", vi: "Hay đấy. Khi nào bạn có thể bắt đầu?" },
    { who: "B", en: "I'm available from next month. Do you have any questions for me — I mean, may I ask about the team?", vi: "Tôi có thể bắt đầu từ tháng sau. Tôi xin hỏi thêm về đội nhóm được không ạ?" },
  ],
},
];

// Câu "can-do": học xong bài này bạn LÀM ĐƯỢC gì (hiển thị đầu mỗi bài học)
const CANDO = {
  greetings: "Chào hỏi, giới thiệu bản thân và hỏi người khác đến từ đâu.",
  family: "Kể về gia đình mình và hỏi về gia đình người khác.",
  "numbers-time": "Hỏi và nói giờ giấc, ngày tháng, sinh nhật.",
  "daily-routine": "Kể về một ngày thường của mình và hỏi thói quen người khác.",
  food: "Đặt bàn, gọi món và thanh toán ở nhà hàng.",
  shopping: "Hỏi giá, mặc thử, mặc cả và trả tiền khi mua sắm.",
  directions: "Hỏi đường, chỉ đường và đi lại bằng phương tiện công cộng.",
  weather: "Nói về thời tiết, mùa và bắt chuyện bằng chủ đề thời tiết.",
  hobbies: "Nói về sở thích, rủ bạn cùng tham gia và từ chối khéo.",
  work: "Giới thiệu nghề nghiệp và trò chuyện về công việc hằng ngày.",
  health: "Mô tả triệu chứng, đặt lịch khám và hiểu lời dặn của bác sĩ.",
  phone: "Gọi điện, nhắn lại lời nhắn và hẹn gặp qua điện thoại.",
  travel: "Đặt phòng, làm thủ tục và hỏi thông tin khi đi du lịch.",
  feelings: "Bày tỏ cảm xúc, an ủi và động viên người khác.",
  money: "Giao dịch ngân hàng, đổi tiền và nói về chi tiêu.",
  study: "Nói về việc học, hỏi lại khi chưa hiểu và cách ghi nhớ từ.",
  sports: "Nói về thể thao, rủ tập luyện và bàn về trận đấu.",
  party: "Mời, nhận/từ chối lời mời và ứng xử tại tiệc.",
  technology: "Xử lý tình huống về điện thoại, wifi và mạng xã hội.",
  emergency: "Kêu cứu, trình báo mất đồ và hỏi đường khi khẩn cấp.",
  smalltalk: "Trò chuyện xã giao với người quen lâu ngày không gặp.",
  "survival-basics": "Hỏi lại khi chưa nghe rõ và xoay xở khi tiếng Anh còn hạn chế.",
  "polite-requests": "Nhờ vả, xin phép và cảm ơn một cách lịch sự.",
  reactions: "Phản ứng tự nhiên với tin vui, tin buồn và điều bất ngờ.",
  opinions: "Hỏi và nêu ý kiến, đồng ý hoặc phản đối lịch sự.",
  "conversation-flow": "Giữ nhịp hội thoại, chuyển chủ đề và câu giờ khi bí từ.",
  "making-friends": "Bắt chuyện với người lạ, xin liên lạc và kết bạn.",
  "coffee-shop": "Gọi đồ uống theo ý mình và trò chuyện ở quán cà phê.",
  "online-order": "Đặt hàng online, hỏi giao hàng và đổi/trả/hoàn tiền.",
  "describing-people": "Mô tả ngoại hình và tính cách của một người.",
  renting: "Hỏi thuê phòng, thương lượng và chốt điều kiện thuê.",
  "job-interview": "Trả lời các câu hỏi phỏng vấn xin việc phổ biến.",
};

// Nạp chủ đề mới vào TOPICS
NEW_TOPICS.forEach(t => { if (!TOPICS.some(x => x.id === t.id)) TOPICS.push(t); });
