// ============================================================
// EnglishDaily — Dữ liệu học (tự động nạp khi mở app)
// 20 chủ đề giao tiếp hằng ngày · level: 1=Cơ bản, 2=Sơ trung, 3=Trung cấp
// ============================================================

const PLACEMENT_TEST = [
  { q: 'Chọn câu chào đúng vào buổi sáng:', opts: ['Good night!', 'Good morning!', 'Goodbye!', 'Good luck!'], a: 1, lv: 1 },
  { q: '"How are you?" — câu trả lời phù hợp là:', opts: ["I'm fine, thank you.", 'I am nine years old.', 'Yes, please.', 'It is Monday.'], a: 0, lv: 1 },
  { q: 'What ___ your name?', opts: ['are', 'am', 'is', 'be'], a: 2, lv: 1 },
  { q: '"Bao nhiêu tiền?" trong tiếng Anh là:', opts: ['How old are you?', 'How much is it?', 'How far is it?', 'What time is it?'], a: 1, lv: 1 },
  { q: 'She ___ to work by bus every day.', opts: ['go', 'goes', 'going', 'gone'], a: 1, lv: 2 },
  { q: 'Chọn từ đúng: "I\'d like to ___ a table for two."', opts: ['book', 'cook', 'look', 'take'], a: 0, lv: 2 },
  { q: '"Could you tell me the way to the bank?" là câu dùng để:', opts: ['Gọi món ăn', 'Hỏi đường', 'Mua vé', 'Xin lỗi'], a: 1, lv: 2 },
  { q: 'I have lived here ___ 2015.', opts: ['for', 'since', 'from', 'at'], a: 1, lv: 3 },
  { q: '"I\'m afraid I can\'t make it to the meeting." nghĩa là:', opts: ['Tôi sợ cuộc họp', 'Tôi không thể tham dự cuộc họp', 'Tôi sẽ tổ chức cuộc họp', 'Tôi làm ra cuộc họp'], a: 1, lv: 3 },
  { q: 'If I ___ you, I would take that job.', opts: ['am', 'was', 'were', 'be'], a: 2, lv: 3 },
];

const TOPICS = [
{
  id: 'greetings', icon: '👋', level: 1,
  name: 'Chào hỏi & Giới thiệu',
  nameEn: 'Greetings & Introductions',
  vocab: [
    { w: 'hello', ipa: '/həˈloʊ/', m: 'xin chào', ex: 'Hello! Nice to meet you.' },
    { w: 'morning', ipa: '/ˈmɔːrnɪŋ/', m: 'buổi sáng', ex: 'Good morning, everyone!' },
    { w: 'name', ipa: '/neɪm/', m: 'tên', ex: 'My name is David.' },
    { w: 'meet', ipa: '/miːt/', m: 'gặp gỡ', ex: 'Nice to meet you.' },
    { w: 'friend', ipa: '/frend/', m: 'bạn bè', ex: 'This is my friend, Anna.' },
    { w: 'country', ipa: '/ˈkʌntri/', m: 'quốc gia', ex: 'Vietnam is a beautiful country.' },
    { w: 'welcome', ipa: '/ˈwelkəm/', m: 'chào mừng', ex: 'Welcome to our class!' },
    { w: 'goodbye', ipa: '/ɡʊdˈbaɪ/', m: 'tạm biệt', ex: 'Goodbye! See you tomorrow.' },
  ],
  phrases: [
    { en: 'Hi! How are you?', vi: 'Chào! Bạn khỏe không?' },
    { en: "I'm fine, thanks. And you?", vi: 'Mình khỏe, cảm ơn. Còn bạn?' },
    { en: 'What is your name?', vi: 'Bạn tên gì?' },
    { en: 'Where are you from?', vi: 'Bạn đến từ đâu?' },
    { en: "I'm from Vietnam.", vi: 'Mình đến từ Việt Nam.' },
    { en: 'Nice to meet you!', vi: 'Rất vui được gặp bạn!' },
    { en: 'See you later!', vi: 'Hẹn gặp lại nhé!' },
  ],
  dialogue: [
    { who: 'A', en: 'Hello! My name is Duong. What is your name?', vi: 'Xin chào! Mình tên Dương. Bạn tên gì?' },
    { who: 'B', en: "Hi Duong! I'm Sarah. Nice to meet you.", vi: 'Chào Dương! Mình là Sarah. Rất vui được gặp bạn.' },
    { who: 'A', en: 'Nice to meet you too. Where are you from?', vi: 'Mình cũng rất vui được gặp bạn. Bạn từ đâu đến?' },
    { who: 'B', en: "I'm from Canada. And you?", vi: 'Mình đến từ Canada. Còn bạn?' },
    { who: 'A', en: "I'm from Vietnam. Welcome to my country!", vi: 'Mình từ Việt Nam. Chào mừng bạn đến đất nước mình!' },
    { who: 'B', en: 'Thank you! Everyone here is so friendly.', vi: 'Cảm ơn! Mọi người ở đây thân thiện quá.' },
  ],
},
{
  id: 'family', icon: '👨‍👩‍👧‍👦', level: 1,
  name: 'Gia đình',
  nameEn: 'Family',
  vocab: [
    { w: 'father', ipa: '/ˈfɑːðər/', m: 'bố, cha', ex: 'My father is a teacher.' },
    { w: 'mother', ipa: '/ˈmʌðər/', m: 'mẹ', ex: 'My mother cooks very well.' },
    { w: 'brother', ipa: '/ˈbrʌðər/', m: 'anh/em trai', ex: 'I have one older brother.' },
    { w: 'sister', ipa: '/ˈsɪstər/', m: 'chị/em gái', ex: 'My sister is a student.' },
    { w: 'parents', ipa: '/ˈperənts/', m: 'bố mẹ', ex: 'I live with my parents.' },
    { w: 'children', ipa: '/ˈtʃɪldrən/', m: 'con cái, trẻ em', ex: 'They have two children.' },
    { w: 'married', ipa: '/ˈmærid/', m: 'đã kết hôn', ex: 'My sister is married.' },
    { w: 'grandparents', ipa: '/ˈɡrænperənts/', m: 'ông bà', ex: 'My grandparents live in the countryside.' },
  ],
  phrases: [
    { en: 'How many people are there in your family?', vi: 'Gia đình bạn có mấy người?' },
    { en: 'There are four people in my family.', vi: 'Gia đình mình có bốn người.' },
    { en: 'Do you have any brothers or sisters?', vi: 'Bạn có anh chị em không?' },
    { en: 'I have a younger sister.', vi: 'Mình có một em gái.' },
    { en: 'What does your father do?', vi: 'Bố bạn làm nghề gì?' },
    { en: 'I live with my parents.', vi: 'Mình sống cùng bố mẹ.' },
  ],
  dialogue: [
    { who: 'A', en: 'Do you have a big family?', vi: 'Gia đình bạn có đông người không?' },
    { who: 'B', en: 'Yes, there are five of us: my parents, two brothers, and me.', vi: 'Có, nhà mình năm người: bố mẹ, hai anh trai và mình.' },
    { who: 'A', en: 'That sounds fun! What do your parents do?', vi: 'Nghe vui đấy! Bố mẹ bạn làm nghề gì?' },
    { who: 'B', en: 'My father is a doctor and my mother is a teacher.', vi: 'Bố mình là bác sĩ, còn mẹ là giáo viên.' },
    { who: 'A', en: 'Do you live with your grandparents too?', vi: 'Bạn có sống cùng ông bà không?' },
    { who: 'B', en: 'No, they live in the countryside, but we visit them every month.', vi: 'Không, ông bà sống ở quê, nhưng nhà mình về thăm mỗi tháng.' },
  ],
},
{
  id: 'numbers-time', icon: '⏰', level: 1,
  name: 'Số đếm, Thời gian & Ngày tháng',
  nameEn: 'Numbers, Time & Dates',
  vocab: [
    { w: 'o’clock', ipa: '/əˈklɑːk/', m: 'giờ (đúng)', ex: 'It is seven o’clock.' },
    { w: 'half past', ipa: '/hæf pæst/', m: 'rưỡi (giờ)', ex: 'It is half past nine.' },
    { w: 'today', ipa: '/təˈdeɪ/', m: 'hôm nay', ex: 'Today is Monday.' },
    { w: 'tomorrow', ipa: '/təˈmɑːroʊ/', m: 'ngày mai', ex: 'See you tomorrow!' },
    { w: 'yesterday', ipa: '/ˈjestərdeɪ/', m: 'hôm qua', ex: 'I was busy yesterday.' },
    { w: 'weekend', ipa: '/ˈwiːkend/', m: 'cuối tuần', ex: 'What do you do on the weekend?' },
    { w: 'early', ipa: '/ˈɜːrli/', m: 'sớm', ex: 'I get up early every day.' },
    { w: 'late', ipa: '/leɪt/', m: 'muộn, trễ', ex: 'Sorry, I am late!' },
  ],
  phrases: [
    { en: 'What time is it?', vi: 'Mấy giờ rồi?' },
    { en: 'It’s half past eight.', vi: 'Tám giờ rưỡi rồi.' },
    { en: 'What day is it today?', vi: 'Hôm nay là thứ mấy?' },
    { en: 'Today is Friday.', vi: 'Hôm nay là thứ Sáu.' },
    { en: 'When is your birthday?', vi: 'Sinh nhật bạn khi nào?' },
    { en: 'My birthday is on May 10th.', vi: 'Sinh nhật mình ngày 10 tháng 5.' },
  ],
  dialogue: [
    { who: 'A', en: 'Excuse me, what time is it?', vi: 'Xin lỗi, mấy giờ rồi ạ?' },
    { who: 'B', en: 'It’s a quarter past ten.', vi: 'Mười giờ mười lăm.' },
    { who: 'A', en: 'Oh no, I’m late for class!', vi: 'Ôi không, mình muộn học rồi!' },
    { who: 'B', en: 'What time does your class start?', vi: 'Lớp bạn bắt đầu lúc mấy giờ?' },
    { who: 'A', en: 'At ten o’clock. I have to run. Thank you!', vi: 'Mười giờ. Mình phải chạy đây. Cảm ơn nhé!' },
    { who: 'B', en: 'Good luck! See you later.', vi: 'Chúc may mắn! Hẹn gặp lại.' },
  ],
},
{
  id: 'daily-routine', icon: '🏠', level: 1,
  name: 'Nhà cửa & Sinh hoạt hằng ngày',
  nameEn: 'Home & Daily Routine',
  vocab: [
    { w: 'wake up', ipa: '/weɪk ʌp/', m: 'thức dậy', ex: 'I wake up at six every morning.' },
    { w: 'breakfast', ipa: '/ˈbrekfəst/', m: 'bữa sáng', ex: 'I have breakfast at home.' },
    { w: 'shower', ipa: '/ˈʃaʊər/', m: 'tắm (vòi sen)', ex: 'I take a shower before work.' },
    { w: 'kitchen', ipa: '/ˈkɪtʃɪn/', m: 'nhà bếp', ex: 'My mother is cooking in the kitchen.' },
    { w: 'bedroom', ipa: '/ˈbedruːm/', m: 'phòng ngủ', ex: 'My bedroom is small but cozy.' },
    { w: 'housework', ipa: '/ˈhaʊswɜːrk/', m: 'việc nhà', ex: 'I do housework on Sundays.' },
    { w: 'go to bed', ipa: '/ɡoʊ tə bed/', m: 'đi ngủ', ex: 'I go to bed at 11 p.m.' },
    { w: 'clean', ipa: '/kliːn/', m: 'dọn dẹp, sạch', ex: 'I clean my room every week.' },
  ],
  phrases: [
    { en: 'What time do you get up?', vi: 'Bạn dậy lúc mấy giờ?' },
    { en: 'I usually get up at six.', vi: 'Mình thường dậy lúc sáu giờ.' },
    { en: 'What do you do in the evening?', vi: 'Buổi tối bạn làm gì?' },
    { en: 'I watch TV and relax.', vi: 'Mình xem TV và thư giãn.' },
    { en: 'I do the housework on weekends.', vi: 'Mình làm việc nhà vào cuối tuần.' },
    { en: 'I go to bed around eleven.', vi: 'Mình đi ngủ khoảng mười một giờ.' },
  ],
  dialogue: [
    { who: 'A', en: 'What does your typical day look like?', vi: 'Một ngày bình thường của bạn thế nào?' },
    { who: 'B', en: 'I wake up at six, take a shower, and have breakfast.', vi: 'Mình dậy lúc sáu giờ, tắm rồi ăn sáng.' },
    { who: 'A', en: 'Do you cook your own breakfast?', vi: 'Bạn tự nấu bữa sáng à?' },
    { who: 'B', en: 'Yes, usually eggs and coffee. Then I go to work at eight.', vi: 'Ừ, thường là trứng và cà phê. Rồi mình đi làm lúc tám giờ.' },
    { who: 'A', en: 'And in the evening?', vi: 'Còn buổi tối thì sao?' },
    { who: 'B', en: 'I have dinner with my family, watch TV, and go to bed at eleven.', vi: 'Mình ăn tối cùng gia đình, xem TV và đi ngủ lúc mười một giờ.' },
  ],
},
{
  id: 'food', icon: '🍜', level: 1,
  name: 'Ăn uống & Nhà hàng',
  nameEn: 'Eating Out',
  vocab: [
    { w: 'menu', ipa: '/ˈmenjuː/', m: 'thực đơn', ex: 'Can I see the menu, please?' },
    { w: 'order', ipa: '/ˈɔːrdər/', m: 'gọi món', ex: 'Are you ready to order?' },
    { w: 'delicious', ipa: '/dɪˈlɪʃəs/', m: 'ngon', ex: 'This soup is delicious!' },
    { w: 'waiter', ipa: '/ˈweɪtər/', m: 'người phục vụ', ex: 'The waiter is very friendly.' },
    { w: 'bill', ipa: '/bɪl/', m: 'hóa đơn', ex: 'Can we have the bill, please?' },
    { w: 'drink', ipa: '/drɪŋk/', m: 'đồ uống', ex: 'What would you like to drink?' },
    { w: 'spicy', ipa: '/ˈspaɪsi/', m: 'cay', ex: 'I love spicy food.' },
    { w: 'dessert', ipa: '/dɪˈzɜːrt/', m: 'món tráng miệng', ex: 'Would you like some dessert?' },
  ],
  phrases: [
    { en: 'A table for two, please.', vi: 'Cho một bàn hai người ạ.' },
    { en: 'Can I see the menu, please?', vi: 'Cho mình xem thực đơn được không?' },
    { en: 'I would like a bowl of pho.', vi: 'Tôi muốn một tô phở.' },
    { en: 'What do you recommend?', vi: 'Bạn gợi ý món gì?' },
    { en: 'The food is delicious!', vi: 'Đồ ăn ngon quá!' },
    { en: 'Can we have the bill, please?', vi: 'Cho chúng tôi thanh toán nhé?' },
  ],
  dialogue: [
    { who: 'A', en: 'Good evening! A table for two, please.', vi: 'Chào buổi tối! Cho một bàn hai người ạ.' },
    { who: 'B', en: 'Of course. This way, please. Here is the menu.', vi: 'Vâng ạ. Mời đi lối này. Đây là thực đơn ạ.' },
    { who: 'A', en: 'Thank you. What do you recommend?', vi: 'Cảm ơn. Bạn gợi ý món gì?' },
    { who: 'B', en: 'The grilled chicken is very popular. It comes with rice and salad.', vi: 'Gà nướng rất được ưa chuộng ạ. Món này kèm cơm và salad.' },
    { who: 'A', en: 'Great, I’ll have that. And a glass of orange juice, please.', vi: 'Tuyệt, cho mình món đó. Và một ly nước cam nhé.' },
    { who: 'B', en: 'Excellent choice! Your food will be ready in ten minutes.', vi: 'Lựa chọn tuyệt vời ạ! Món ăn sẽ ra trong mười phút nữa.' },
  ],
},
{
  id: 'shopping', icon: '🛍️', level: 1,
  name: 'Mua sắm',
  nameEn: 'Shopping',
  vocab: [
    { w: 'price', ipa: '/praɪs/', m: 'giá cả', ex: 'What is the price of this shirt?' },
    { w: 'expensive', ipa: '/ɪkˈspensɪv/', m: 'đắt', ex: 'This bag is too expensive.' },
    { w: 'cheap', ipa: '/tʃiːp/', m: 'rẻ', ex: 'The market is cheaper than the mall.' },
    { w: 'size', ipa: '/saɪz/', m: 'kích cỡ', ex: 'Do you have this in size M?' },
    { w: 'try on', ipa: '/traɪ ɑːn/', m: 'mặc thử', ex: 'Can I try on this dress?' },
    { w: 'discount', ipa: '/ˈdɪskaʊnt/', m: 'giảm giá', ex: 'Is there a discount today?' },
    { w: 'cash', ipa: '/kæʃ/', m: 'tiền mặt', ex: 'I will pay in cash.' },
    { w: 'receipt', ipa: '/rɪˈsiːt/', m: 'biên lai', ex: 'Here is your receipt.' },
  ],
  phrases: [
    { en: 'How much is this?', vi: 'Cái này bao nhiêu tiền?' },
    { en: 'Do you have this in a larger size?', vi: 'Có cỡ lớn hơn không?' },
    { en: 'Can I try it on?', vi: 'Mình mặc thử được không?' },
    { en: 'It’s too expensive. Can you give me a discount?', vi: 'Đắt quá. Giảm giá được không?' },
    { en: 'I’ll take it.', vi: 'Mình lấy cái này.' },
    { en: 'Can I pay by card?', vi: 'Mình trả bằng thẻ được không?' },
  ],
  dialogue: [
    { who: 'A', en: 'Excuse me, how much is this T-shirt?', vi: 'Xin lỗi, cái áo phông này bao nhiêu tiền?' },
    { who: 'B', en: 'It’s twenty dollars, but today we have a 20% discount.', vi: 'Hai mươi đô, nhưng hôm nay giảm giá 20% ạ.' },
    { who: 'A', en: 'Nice! Do you have it in size L?', vi: 'Tuyệt! Có cỡ L không?' },
    { who: 'B', en: 'Yes, we do. The fitting room is over there.', vi: 'Có ạ. Phòng thử đồ ở đằng kia.' },
    { who: 'A', en: 'It fits perfectly. I’ll take it. Can I pay by card?', vi: 'Vừa in luôn. Mình lấy nhé. Trả bằng thẻ được không?' },
    { who: 'B', en: 'Of course. Here is your receipt. Have a nice day!', vi: 'Được ạ. Đây là biên lai. Chúc một ngày tốt lành!' },
  ],
},
{
  id: 'directions', icon: '🧭', level: 2,
  name: 'Hỏi đường & Phương tiện',
  nameEn: 'Directions & Transport',
  vocab: [
    { w: 'turn left', ipa: '/tɜːrn left/', m: 'rẽ trái', ex: 'Turn left at the corner.' },
    { w: 'turn right', ipa: '/tɜːrn raɪt/', m: 'rẽ phải', ex: 'Turn right at the traffic light.' },
    { w: 'straight', ipa: '/streɪt/', m: 'thẳng', ex: 'Go straight for two blocks.' },
    { w: 'crossroads', ipa: '/ˈkrɔːsroʊdz/', m: 'ngã tư', ex: 'The bank is at the crossroads.' },
    { w: 'bus stop', ipa: '/bʌs stɑːp/', m: 'trạm xe buýt', ex: 'The bus stop is near my house.' },
    { w: 'ticket', ipa: '/ˈtɪkɪt/', m: 'vé', ex: 'A ticket to the city center, please.' },
    { w: 'far', ipa: '/fɑːr/', m: 'xa', ex: 'Is it far from here?' },
    { w: 'get off', ipa: '/ɡet ɔːf/', m: 'xuống xe', ex: 'Get off at the next stop.' },
  ],
  phrases: [
    { en: 'Excuse me, where is the nearest bank?', vi: 'Xin lỗi, ngân hàng gần nhất ở đâu ạ?' },
    { en: 'Go straight and turn left at the corner.', vi: 'Đi thẳng rồi rẽ trái ở góc phố.' },
    { en: 'How far is it from here?', vi: 'Từ đây tới đó bao xa?' },
    { en: 'It’s about ten minutes on foot.', vi: 'Đi bộ khoảng mười phút.' },
    { en: 'Which bus goes to the airport?', vi: 'Xe buýt nào đi sân bay?' },
    { en: 'You should take a taxi.', vi: 'Bạn nên đi taxi.' },
  ],
  dialogue: [
    { who: 'A', en: 'Excuse me, could you tell me the way to the train station?', vi: 'Xin lỗi, chỉ giúp mình đường đến ga tàu được không?' },
    { who: 'B', en: 'Sure. Go straight along this street, then turn right at the second crossroads.', vi: 'Được chứ. Đi thẳng phố này, rồi rẽ phải ở ngã tư thứ hai.' },
    { who: 'A', en: 'Is it far from here?', vi: 'Từ đây có xa không ạ?' },
    { who: 'B', en: 'Not really, about fifteen minutes on foot. Or you can take bus number 9.', vi: 'Không xa lắm, đi bộ khoảng mười lăm phút. Hoặc bạn đi xe buýt số 9.' },
    { who: 'A', en: 'Where is the bus stop?', vi: 'Trạm xe buýt ở đâu ạ?' },
    { who: 'B', en: 'Right over there, next to the coffee shop.', vi: 'Ngay đằng kia, cạnh quán cà phê.' },
  ],
},
{
  id: 'weather', icon: '⛅', level: 2,
  name: 'Thời tiết & Mùa',
  nameEn: 'Weather & Seasons',
  vocab: [
    { w: 'sunny', ipa: '/ˈsʌni/', m: 'nắng', ex: 'It’s sunny today.' },
    { w: 'rainy', ipa: '/ˈreɪni/', m: 'mưa', ex: 'Take an umbrella, it’s rainy.' },
    { w: 'cloudy', ipa: '/ˈklaʊdi/', m: 'nhiều mây', ex: 'The sky is cloudy this morning.' },
    { w: 'hot', ipa: '/hɑːt/', m: 'nóng', ex: 'Summer here is very hot.' },
    { w: 'cold', ipa: '/koʊld/', m: 'lạnh', ex: 'It gets cold in December.' },
    { w: 'forecast', ipa: '/ˈfɔːrkæst/', m: 'dự báo', ex: 'The forecast says it will rain.' },
    { w: 'temperature', ipa: '/ˈtemprətʃər/', m: 'nhiệt độ', ex: 'The temperature is 35 degrees.' },
    { w: 'umbrella', ipa: '/ʌmˈbrelə/', m: 'ô, dù', ex: 'Don’t forget your umbrella!' },
  ],
  phrases: [
    { en: 'What’s the weather like today?', vi: 'Hôm nay thời tiết thế nào?' },
    { en: 'It’s hot and sunny.', vi: 'Trời nóng và nắng.' },
    { en: 'It looks like it’s going to rain.', vi: 'Trông như trời sắp mưa.' },
    { en: 'What’s your favorite season?', vi: 'Bạn thích mùa nào nhất?' },
    { en: 'I love autumn because it’s cool.', vi: 'Mình thích mùa thu vì trời mát.' },
    { en: 'Don’t forget to bring an umbrella.', vi: 'Đừng quên mang ô nhé.' },
  ],
  dialogue: [
    { who: 'A', en: 'What’s the weather like in your hometown?', vi: 'Thời tiết ở quê bạn thế nào?' },
    { who: 'B', en: 'It’s hot all year round, and it rains a lot from May to November.', vi: 'Nóng quanh năm, và mưa nhiều từ tháng Năm đến tháng Mười Một.' },
    { who: 'A', en: 'Wow, so you don’t have winter?', vi: 'Ồ, vậy chỗ bạn không có mùa đông à?' },
    { who: 'B', en: 'Not really. What about your city?', vi: 'Không hẳn. Thế còn thành phố của bạn?' },
    { who: 'A', en: 'We have four seasons. Winter is very cold, sometimes it snows.', vi: 'Chỗ mình có bốn mùa. Mùa đông rất lạnh, thi thoảng có tuyết.' },
    { who: 'B', en: 'I’d love to see snow one day!', vi: 'Mình mong một ngày được thấy tuyết!' },
  ],
},
{
  id: 'hobbies', icon: '🎸', level: 2,
  name: 'Sở thích & Thời gian rảnh',
  nameEn: 'Hobbies & Free Time',
  vocab: [
    { w: 'hobby', ipa: '/ˈhɑːbi/', m: 'sở thích', ex: 'My hobby is playing guitar.' },
    { w: 'free time', ipa: '/friː taɪm/', m: 'thời gian rảnh', ex: 'What do you do in your free time?' },
    { w: 'reading', ipa: '/ˈriːdɪŋ/', m: 'đọc sách', ex: 'Reading helps me relax.' },
    { w: 'travel', ipa: '/ˈtrævl/', m: 'du lịch', ex: 'I love to travel with friends.' },
    { w: 'movie', ipa: '/ˈmuːvi/', m: 'phim', ex: 'Let’s watch a movie tonight.' },
    { w: 'music', ipa: '/ˈmjuːzɪk/', m: 'âm nhạc', ex: 'I listen to music every day.' },
    { w: 'photography', ipa: '/fəˈtɑːɡrəfi/', m: 'nhiếp ảnh', ex: 'Photography is my new hobby.' },
    { w: 'relax', ipa: '/rɪˈlæks/', m: 'thư giãn', ex: 'I relax by cooking.' },
  ],
  phrases: [
    { en: 'What do you do in your free time?', vi: 'Lúc rảnh bạn làm gì?' },
    { en: 'I usually listen to music and read books.', vi: 'Mình thường nghe nhạc và đọc sách.' },
    { en: 'Are you into sports?', vi: 'Bạn có thích thể thao không?' },
    { en: 'I’m really into photography.', vi: 'Mình rất mê nhiếp ảnh.' },
    { en: 'How often do you go to the movies?', vi: 'Bạn có hay đi xem phim không?' },
    { en: 'Let’s hang out this weekend!', vi: 'Cuối tuần này đi chơi nhé!' },
  ],
  dialogue: [
    { who: 'A', en: 'What do you usually do in your free time?', vi: 'Lúc rảnh bạn thường làm gì?' },
    { who: 'B', en: 'I love taking photos. I go around the city with my camera every weekend.', vi: 'Mình thích chụp ảnh. Cuối tuần nào mình cũng mang máy ảnh đi khắp thành phố.' },
    { who: 'A', en: 'That sounds interesting! How long have you been doing that?', vi: 'Nghe thú vị đấy! Bạn chơi ảnh bao lâu rồi?' },
    { who: 'B', en: 'About two years. What about you? Any hobbies?', vi: 'Khoảng hai năm. Còn bạn? Có sở thích gì không?' },
    { who: 'A', en: 'I play guitar and sometimes write my own songs.', vi: 'Mình chơi guitar và thi thoảng tự viết nhạc.' },
    { who: 'B', en: 'Cool! We should do a photo-music project together!', vi: 'Hay quá! Bọn mình nên làm chung một dự án ảnh - nhạc đi!' },
  ],
},
{
  id: 'work', icon: '💼', level: 2,
  name: 'Công việc & Nghề nghiệp',
  nameEn: 'Work & Jobs',
  vocab: [
    { w: 'job', ipa: '/dʒɑːb/', m: 'công việc', ex: 'I’m looking for a new job.' },
    { w: 'office', ipa: '/ˈɔːfɪs/', m: 'văn phòng', ex: 'My office is in the city center.' },
    { w: 'meeting', ipa: '/ˈmiːtɪŋ/', m: 'cuộc họp', ex: 'I have a meeting at 2 p.m.' },
    { w: 'salary', ipa: '/ˈsæləri/', m: 'lương', ex: 'The salary is quite good.' },
    { w: 'colleague', ipa: '/ˈkɑːliːɡ/', m: 'đồng nghiệp', ex: 'My colleagues are friendly.' },
    { w: 'busy', ipa: '/ˈbɪzi/', m: 'bận rộn', ex: 'I’m very busy this week.' },
    { w: 'deadline', ipa: '/ˈdedlaɪn/', m: 'hạn chót', ex: 'The deadline is Friday.' },
    { w: 'interview', ipa: '/ˈɪntərvjuː/', m: 'phỏng vấn', ex: 'I have a job interview tomorrow.' },
  ],
  phrases: [
    { en: 'What do you do for a living?', vi: 'Bạn làm nghề gì?' },
    { en: 'I work as a teacher.', vi: 'Mình là giáo viên.' },
    { en: 'Where do you work?', vi: 'Bạn làm việc ở đâu?' },
    { en: 'I’ve been working there for three years.', vi: 'Mình làm ở đó được ba năm rồi.' },
    { en: 'Do you like your job?', vi: 'Bạn có thích công việc của mình không?' },
    { en: 'I’m busy with a big project right now.', vi: 'Dạo này mình bận một dự án lớn.' },
  ],
  dialogue: [
    { who: 'A', en: 'So, what do you do for a living?', vi: 'Vậy bạn làm nghề gì?' },
    { who: 'B', en: 'I’m a math teacher at a high school. How about you?', vi: 'Mình là giáo viên Toán ở một trường cấp ba. Còn bạn?' },
    { who: 'A', en: 'I work in marketing for a tech company.', vi: 'Mình làm marketing cho một công ty công nghệ.' },
    { who: 'B', en: 'That sounds exciting! Do you enjoy it?', vi: 'Nghe hấp dẫn đấy! Bạn có thích không?' },
    { who: 'A', en: 'Yes, but it’s quite busy. We have deadlines every week.', vi: 'Thích, nhưng khá bận. Tuần nào cũng có hạn chót.' },
    { who: 'B', en: 'Teaching is busy too, but seeing students improve makes me happy.', vi: 'Dạy học cũng bận lắm, nhưng thấy học sinh tiến bộ là mình vui.' },
  ],
},
{
  id: 'health', icon: '🏥', level: 2,
  name: 'Sức khỏe & Khám bệnh',
  nameEn: 'Health & Doctor',
  vocab: [
    { w: 'headache', ipa: '/ˈhedeɪk/', m: 'đau đầu', ex: 'I have a headache.' },
    { w: 'fever', ipa: '/ˈfiːvər/', m: 'sốt', ex: 'She has a high fever.' },
    { w: 'cough', ipa: '/kɔːf/', m: 'ho', ex: 'I can’t stop coughing.' },
    { w: 'medicine', ipa: '/ˈmedɪsn/', m: 'thuốc', ex: 'Take this medicine twice a day.' },
    { w: 'doctor', ipa: '/ˈdɑːktər/', m: 'bác sĩ', ex: 'You should see a doctor.' },
    { w: 'pharmacy', ipa: '/ˈfɑːrməsi/', m: 'hiệu thuốc', ex: 'Is there a pharmacy near here?' },
    { w: 'rest', ipa: '/rest/', m: 'nghỉ ngơi', ex: 'You need to get some rest.' },
    { w: 'appointment', ipa: '/əˈpɔɪntmənt/', m: 'lịch hẹn', ex: 'I’d like to make an appointment.' },
  ],
  phrases: [
    { en: 'I don’t feel well.', vi: 'Mình thấy không khỏe.' },
    { en: 'What’s the matter?', vi: 'Bạn bị sao vậy?' },
    { en: 'I have a sore throat and a fever.', vi: 'Mình bị đau họng và sốt.' },
    { en: 'How long have you felt like this?', vi: 'Bạn bị thế này bao lâu rồi?' },
    { en: 'Take this medicine three times a day.', vi: 'Uống thuốc này ngày ba lần.' },
    { en: 'Get well soon!', vi: 'Mau khỏe nhé!' },
  ],
  dialogue: [
    { who: 'A', en: 'Good morning, doctor. I don’t feel well.', vi: 'Chào bác sĩ. Tôi thấy không khỏe.' },
    { who: 'B', en: 'What seems to be the problem?', vi: 'Anh bị làm sao?' },
    { who: 'A', en: 'I have a headache, a sore throat, and I feel tired.', vi: 'Tôi đau đầu, đau họng và thấy mệt.' },
    { who: 'B', en: 'How long have you had these symptoms?', vi: 'Anh có các triệu chứng này bao lâu rồi?' },
    { who: 'A', en: 'Since yesterday morning.', vi: 'Từ sáng hôm qua.' },
    { who: 'B', en: 'It’s just a cold. Take this medicine and rest for two days.', vi: 'Chỉ là cảm thôi. Uống thuốc này và nghỉ ngơi hai ngày nhé.' },
  ],
},
{
  id: 'phone', icon: '📞', level: 2,
  name: 'Điện thoại & Hẹn gặp',
  nameEn: 'Phone Calls & Appointments',
  vocab: [
    { w: 'call back', ipa: '/kɔːl bæk/', m: 'gọi lại', ex: 'Can I call you back later?' },
    { w: 'message', ipa: '/ˈmesɪdʒ/', m: 'tin nhắn', ex: 'Please leave a message.' },
    { w: 'hold on', ipa: '/hoʊld ɑːn/', m: 'giữ máy, chờ chút', ex: 'Hold on a second, please.' },
    { w: 'available', ipa: '/əˈveɪləbl/', m: 'rảnh, có mặt', ex: 'Are you available on Friday?' },
    { w: 'schedule', ipa: '/ˈskedʒuːl/', m: 'lịch trình', ex: 'Let me check my schedule.' },
    { w: 'cancel', ipa: '/ˈkænsl/', m: 'hủy', ex: 'I need to cancel our meeting.' },
    { w: 'confirm', ipa: '/kənˈfɜːrm/', m: 'xác nhận', ex: 'I’m calling to confirm my appointment.' },
    { w: 'wrong number', ipa: '/rɔːŋ ˈnʌmbər/', m: 'nhầm số', ex: 'Sorry, you have the wrong number.' },
  ],
  phrases: [
    { en: 'Hello, may I speak to Mr. Smith?', vi: 'Alô, cho tôi gặp ông Smith được không?' },
    { en: 'Who’s calling, please?', vi: 'Xin hỏi ai đang gọi ạ?' },
    { en: 'Hold on a moment, please.', vi: 'Vui lòng giữ máy một chút.' },
    { en: 'Can I leave a message?', vi: 'Tôi nhắn lại được không?' },
    { en: 'Are you free on Saturday afternoon?', vi: 'Chiều thứ Bảy bạn có rảnh không?' },
    { en: 'Let’s meet at 7 p.m. at the coffee shop.', vi: 'Gặp nhau lúc 7 giờ tối ở quán cà phê nhé.' },
  ],
  dialogue: [
    { who: 'A', en: 'Hello, this is Duong. May I speak to Ms. Lee?', vi: 'Alô, tôi là Dương. Cho tôi gặp cô Lee được không?' },
    { who: 'B', en: 'I’m sorry, she’s in a meeting right now. Can I take a message?', vi: 'Xin lỗi, cô ấy đang họp. Anh có muốn nhắn gì không?' },
    { who: 'A', en: 'Yes, please. Could you ask her to call me back this afternoon?', vi: 'Vâng. Nhờ chị nhắn cô ấy gọi lại cho tôi chiều nay nhé?' },
    { who: 'B', en: 'Sure. Does she have your number?', vi: 'Được ạ. Cô ấy có số của anh chưa?' },
    { who: 'A', en: 'Yes, she does. It’s about tomorrow’s appointment.', vi: 'Có rồi ạ. Là về lịch hẹn ngày mai.' },
    { who: 'B', en: 'Got it. I’ll let her know as soon as she’s free.', vi: 'Vâng. Tôi sẽ báo cô ấy ngay khi cô ấy rảnh.' },
  ],
},
{
  id: 'travel', icon: '✈️', level: 2,
  name: 'Du lịch & Khách sạn',
  nameEn: 'Travel & Hotel',
  vocab: [
    { w: 'passport', ipa: '/ˈpæspɔːrt/', m: 'hộ chiếu', ex: 'May I see your passport?' },
    { w: 'luggage', ipa: '/ˈlʌɡɪdʒ/', m: 'hành lý', ex: 'My luggage is very heavy.' },
    { w: 'book', ipa: '/bʊk/', m: 'đặt (phòng, vé)', ex: 'I booked a room online.' },
    { w: 'check in', ipa: '/tʃek ɪn/', m: 'nhận phòng / làm thủ tục', ex: 'What time can I check in?' },
    { w: 'reception', ipa: '/rɪˈsepʃn/', m: 'quầy lễ tân', ex: 'Ask at the reception desk.' },
    { w: 'flight', ipa: '/flaɪt/', m: 'chuyến bay', ex: 'My flight leaves at 9 a.m.' },
    { w: 'sightseeing', ipa: '/ˈsaɪtsiːɪŋ/', m: 'tham quan', ex: 'We went sightseeing all day.' },
    { w: 'souvenir', ipa: '/ˌsuːvəˈnɪr/', m: 'quà lưu niệm', ex: 'I bought some souvenirs for my family.' },
  ],
  phrases: [
    { en: 'I’d like to book a room for two nights.', vi: 'Tôi muốn đặt phòng hai đêm.' },
    { en: 'Do you have any rooms available?', vi: 'Còn phòng trống không ạ?' },
    { en: 'What time is check-out?', vi: 'Mấy giờ trả phòng?' },
    { en: 'Is breakfast included?', vi: 'Có bao gồm bữa sáng không?' },
    { en: 'Where is the nearest tourist attraction?', vi: 'Điểm tham quan gần nhất ở đâu?' },
    { en: 'Could you call a taxi for me?', vi: 'Gọi giúp tôi một chiếc taxi được không?' },
  ],
  dialogue: [
    { who: 'A', en: 'Good afternoon! I have a reservation under the name Duong.', vi: 'Chào buổi chiều! Tôi có đặt phòng dưới tên Dương.' },
    { who: 'B', en: 'Welcome! Yes, a double room for three nights. May I see your passport?', vi: 'Chào mừng quý khách! Vâng, phòng đôi ba đêm. Cho tôi xem hộ chiếu ạ?' },
    { who: 'A', en: 'Here you are. Is breakfast included?', vi: 'Đây ạ. Có kèm bữa sáng không?' },
    { who: 'B', en: 'Yes, breakfast is served from 6 to 10 a.m. on the first floor.', vi: 'Có ạ, bữa sáng phục vụ từ 6 đến 10 giờ ở tầng một.' },
    { who: 'A', en: 'Great. Could you recommend some places for sightseeing?', vi: 'Tuyệt. Bạn gợi ý giúp vài chỗ tham quan được không?' },
    { who: 'B', en: 'Of course! Here is a city map. The old town is a must-see.', vi: 'Được ạ! Đây là bản đồ thành phố. Phố cổ là nơi nhất định phải ghé.' },
  ],
},
{
  id: 'feelings', icon: '💬', level: 2,
  name: 'Cảm xúc & Nêu ý kiến',
  nameEn: 'Feelings & Opinions',
  vocab: [
    { w: 'happy', ipa: '/ˈhæpi/', m: 'vui, hạnh phúc', ex: 'I’m so happy to see you!' },
    { w: 'tired', ipa: '/ˈtaɪərd/', m: 'mệt', ex: 'I’m tired after work.' },
    { w: 'worried', ipa: '/ˈwɜːrid/', m: 'lo lắng', ex: 'Don’t be worried about the exam.' },
    { w: 'excited', ipa: '/ɪkˈsaɪtɪd/', m: 'háo hức', ex: 'I’m excited about the trip.' },
    { w: 'agree', ipa: '/əˈɡriː/', m: 'đồng ý', ex: 'I agree with you.' },
    { w: 'disagree', ipa: '/ˌdɪsəˈɡriː/', m: 'không đồng ý', ex: 'I’m afraid I disagree.' },
    { w: 'opinion', ipa: '/əˈpɪnjən/', m: 'ý kiến', ex: 'In my opinion, it’s a great idea.' },
    { w: 'surprised', ipa: '/sərˈpraɪzd/', m: 'ngạc nhiên', ex: 'I was surprised by the news.' },
  ],
  phrases: [
    { en: 'How do you feel today?', vi: 'Hôm nay bạn thấy thế nào?' },
    { en: 'I’m a bit tired, but I’m okay.', vi: 'Mình hơi mệt, nhưng vẫn ổn.' },
    { en: 'What do you think about it?', vi: 'Bạn nghĩ sao về việc đó?' },
    { en: 'In my opinion, it’s a good idea.', vi: 'Theo mình, đó là ý hay.' },
    { en: 'I totally agree with you.', vi: 'Mình hoàn toàn đồng ý với bạn.' },
    { en: 'I see your point, but I think differently.', vi: 'Mình hiểu ý bạn, nhưng mình nghĩ khác.' },
  ],
  dialogue: [
    { who: 'A', en: 'You look really happy today. What happened?', vi: 'Hôm nay trông bạn vui thế. Có chuyện gì vậy?' },
    { who: 'B', en: 'I passed my driving test! I’m so excited!', vi: 'Mình thi đỗ bằng lái rồi! Háo hức quá!' },
    { who: 'A', en: 'Congratulations! I knew you could do it.', vi: 'Chúc mừng nhé! Mình biết bạn làm được mà.' },
    { who: 'B', en: 'Thanks! Honestly, I was so worried before the test.', vi: 'Cảm ơn! Thật ra trước khi thi mình lo lắm.' },
    { who: 'A', en: 'In my opinion, you’re a careful driver already.', vi: 'Theo mình thấy, bạn lái xe cẩn thận sẵn rồi.' },
    { who: 'B', en: 'That’s kind of you. Let’s celebrate this weekend!', vi: 'Bạn tốt quá. Cuối tuần này ăn mừng nhé!' },
  ],
},
{
  id: 'money', icon: '🏦', level: 3,
  name: 'Ngân hàng & Tiền bạc',
  nameEn: 'Money & Banking',
  vocab: [
    { w: 'account', ipa: '/əˈkaʊnt/', m: 'tài khoản', ex: 'I’d like to open a bank account.' },
    { w: 'transfer', ipa: '/ˈtrænsfɜːr/', m: 'chuyển khoản', ex: 'Can I transfer money online?' },
    { w: 'withdraw', ipa: '/wɪðˈdrɔː/', m: 'rút tiền', ex: 'I need to withdraw some cash.' },
    { w: 'deposit', ipa: '/dɪˈpɑːzɪt/', m: 'gửi tiền', ex: 'She made a deposit of $500.' },
    { w: 'exchange rate', ipa: '/ɪksˈtʃeɪndʒ reɪt/', m: 'tỷ giá', ex: 'What’s the exchange rate today?' },
    { w: 'save', ipa: '/seɪv/', m: 'tiết kiệm', ex: 'I save 20% of my salary every month.' },
    { w: 'borrow', ipa: '/ˈbɑːroʊ/', m: 'vay, mượn', ex: 'Can I borrow some money?' },
    { w: 'budget', ipa: '/ˈbʌdʒɪt/', m: 'ngân sách', ex: 'We’re on a tight budget this month.' },
  ],
  phrases: [
    { en: 'I’d like to open a savings account.', vi: 'Tôi muốn mở tài khoản tiết kiệm.' },
    { en: 'What documents do I need?', vi: 'Tôi cần những giấy tờ gì?' },
    { en: 'I’d like to exchange dollars for dong.', vi: 'Tôi muốn đổi đô la sang tiền đồng.' },
    { en: 'What’s the exchange rate today?', vi: 'Tỷ giá hôm nay là bao nhiêu?' },
    { en: 'Where is the nearest ATM?', vi: 'Cây ATM gần nhất ở đâu?' },
    { en: 'I’m trying to save money for a trip.', vi: 'Mình đang cố tiết kiệm tiền để đi du lịch.' },
  ],
  dialogue: [
    { who: 'A', en: 'Good morning. I’d like to open a bank account, please.', vi: 'Chào buổi sáng. Tôi muốn mở tài khoản ngân hàng ạ.' },
    { who: 'B', en: 'Certainly. Would you like a checking or a savings account?', vi: 'Vâng ạ. Anh muốn mở tài khoản thanh toán hay tiết kiệm?' },
    { who: 'A', en: 'A savings account. What’s the interest rate?', vi: 'Tài khoản tiết kiệm. Lãi suất là bao nhiêu vậy?' },
    { who: 'B', en: 'It’s 4.5% per year. I’ll need your ID and proof of address.', vi: 'Là 4,5% một năm ạ. Tôi cần CMND/CCCD và giấy tờ chứng minh địa chỉ của anh.' },
    { who: 'A', en: 'Here you are. Can I also use mobile banking?', vi: 'Đây ạ. Tôi dùng được ngân hàng trên điện thoại chứ?' },
    { who: 'B', en: 'Yes, I’ll help you set up the app right after this.', vi: 'Được ạ, tôi sẽ giúp anh cài ứng dụng ngay sau đây.' },
  ],
},
{
  id: 'study', icon: '🎓', level: 3,
  name: 'Học tập & Trường lớp',
  nameEn: 'School & Study',
  vocab: [
    { w: 'subject', ipa: '/ˈsʌbdʒɪkt/', m: 'môn học', ex: 'Math is my favorite subject.' },
    { w: 'exam', ipa: '/ɪɡˈzæm/', m: 'kỳ thi', ex: 'I have an exam next week.' },
    { w: 'homework', ipa: '/ˈhoʊmwɜːrk/', m: 'bài tập về nhà', ex: 'Have you finished your homework?' },
    { w: 'grade', ipa: '/ɡreɪd/', m: 'điểm số, lớp', ex: 'She got a good grade in English.' },
    { w: 'scholarship', ipa: '/ˈskɑːlərʃɪp/', m: 'học bổng', ex: 'He won a scholarship to study abroad.' },
    { w: 'improve', ipa: '/ɪmˈpruːv/', m: 'cải thiện', ex: 'I want to improve my speaking skills.' },
    { w: 'practice', ipa: '/ˈpræktɪs/', m: 'luyện tập', ex: 'Practice makes perfect.' },
    { w: 'memorize', ipa: '/ˈmeməraɪz/', m: 'ghi nhớ, học thuộc', ex: 'I memorize ten new words a day.' },
  ],
  phrases: [
    { en: 'What are you studying?', vi: 'Bạn đang học ngành gì?' },
    { en: 'How do you learn new vocabulary?', vi: 'Bạn học từ mới thế nào?' },
    { en: 'I review my notes every evening.', vi: 'Tối nào mình cũng xem lại bài.' },
    { en: 'Could you explain that again, please?', vi: 'Bạn giải thích lại giúp mình được không?' },
    { en: 'I’m preparing for an important exam.', vi: 'Mình đang ôn cho một kỳ thi quan trọng.' },
    { en: 'Practice a little every day — it really works.', vi: 'Mỗi ngày luyện một chút — hiệu quả thật đấy.' },
  ],
  dialogue: [
    { who: 'A', en: 'How is your English study going?', vi: 'Việc học tiếng Anh của bạn sao rồi?' },
    { who: 'B', en: 'Pretty well! I practice speaking fifteen minutes every day.', vi: 'Khá tốt! Ngày nào mình cũng luyện nói mười lăm phút.' },
    { who: 'A', en: 'That’s a great habit. How do you memorize new words?', vi: 'Thói quen tốt đấy. Bạn ghi nhớ từ mới bằng cách nào?' },
    { who: 'B', en: 'I use flashcards and review them before bed.', vi: 'Mình dùng flashcard và ôn lại trước khi ngủ.' },
    { who: 'A', en: 'Does it really help?', vi: 'Có hiệu quả thật không?' },
    { who: 'B', en: 'Absolutely. My vocabulary has improved a lot in two months.', vi: 'Chắc chắn rồi. Vốn từ của mình tiến bộ nhiều chỉ trong hai tháng.' },
  ],
},
{
  id: 'sports', icon: '⚽', level: 3,
  name: 'Thể thao & Rèn luyện',
  nameEn: 'Sports & Fitness',
  vocab: [
    { w: 'exercise', ipa: '/ˈeksərsaɪz/', m: 'tập thể dục', ex: 'I exercise three times a week.' },
    { w: 'gym', ipa: '/dʒɪm/', m: 'phòng tập', ex: 'He goes to the gym after work.' },
    { w: 'jogging', ipa: '/ˈdʒɑːɡɪŋ/', m: 'chạy bộ', ex: 'Jogging in the morning is refreshing.' },
    { w: 'team', ipa: '/tiːm/', m: 'đội', ex: 'Our team won the match!' },
    { w: 'match', ipa: '/mætʃ/', m: 'trận đấu', ex: 'Did you watch the match last night?' },
    { w: 'score', ipa: '/skɔːr/', m: 'tỷ số, ghi điểm', ex: 'What was the final score?' },
    { w: 'healthy', ipa: '/ˈhelθi/', m: 'khỏe mạnh', ex: 'Eating vegetables keeps you healthy.' },
    { w: 'stretch', ipa: '/stretʃ/', m: 'giãn cơ', ex: 'Always stretch before running.' },
  ],
  phrases: [
    { en: 'Do you play any sports?', vi: 'Bạn có chơi môn thể thao nào không?' },
    { en: 'I play football every Sunday.', vi: 'Chủ nhật nào mình cũng đá bóng.' },
    { en: 'How often do you work out?', vi: 'Bạn tập luyện bao lâu một lần?' },
    { en: 'I go jogging every morning.', vi: 'Sáng nào mình cũng chạy bộ.' },
    { en: 'Did you watch the game last night?', vi: 'Tối qua bạn có xem trận đấu không?' },
    { en: 'We won two to one!', vi: 'Bọn mình thắng 2-1!' },
  ],
  dialogue: [
    { who: 'A', en: 'You look really fit these days. What’s your secret?', vi: 'Dạo này trông bạn khỏe khoắn thật đấy. Bí quyết là gì vậy?' },
    { who: 'B', en: 'I started going to the gym three months ago.', vi: 'Mình bắt đầu đi tập gym ba tháng trước.' },
    { who: 'A', en: 'How often do you go?', vi: 'Bạn đi tập mấy buổi một tuần?' },
    { who: 'B', en: 'Four times a week, and I jog on the other days.', vi: 'Bốn buổi một tuần, những ngày còn lại thì chạy bộ.' },
    { who: 'A', en: 'Impressive! Maybe I should join you.', vi: 'Nể thật! Chắc mình cũng nên tập cùng bạn.' },
    { who: 'B', en: 'You should! Exercising with a friend is much more fun.', vi: 'Tập đi! Tập cùng bạn bè vui hơn nhiều.' },
  ],
},
{
  id: 'party', icon: '🎉', level: 3,
  name: 'Tiệc tùng & Lễ hội',
  nameEn: 'Parties & Celebrations',
  vocab: [
    { w: 'invite', ipa: '/ɪnˈvaɪt/', m: 'mời', ex: 'They invited us to their wedding.' },
    { w: 'celebrate', ipa: '/ˈselɪbreɪt/', m: 'ăn mừng', ex: 'Let’s celebrate your promotion!' },
    { w: 'gift', ipa: '/ɡɪft/', m: 'quà tặng', ex: 'I bought a gift for her birthday.' },
    { w: 'wedding', ipa: '/ˈwedɪŋ/', m: 'đám cưới', ex: 'The wedding was beautiful.' },
    { w: 'festival', ipa: '/ˈfestɪvl/', m: 'lễ hội', ex: 'Tet is the biggest festival in Vietnam.' },
    { w: 'decorate', ipa: '/ˈdekəreɪt/', m: 'trang trí', ex: 'We decorated the house for the party.' },
    { w: 'guest', ipa: '/ɡest/', m: 'khách mời', ex: 'There were fifty guests at the party.' },
    { w: 'toast', ipa: '/toʊst/', m: 'nâng ly chúc mừng', ex: 'Let’s make a toast to the happy couple!' },
  ],
  phrases: [
    { en: 'Would you like to come to my birthday party?', vi: 'Bạn đến dự sinh nhật mình nhé?' },
    { en: 'I’d love to! When is it?', vi: 'Mình rất thích! Khi nào vậy?' },
    { en: 'Happy birthday! This is for you.', vi: 'Chúc mừng sinh nhật! Quà cho bạn này.' },
    { en: 'Congratulations on your wedding!', vi: 'Chúc mừng đám cưới của bạn!' },
    { en: 'Thanks for inviting me.', vi: 'Cảm ơn đã mời mình.' },
    { en: 'I had a great time tonight!', vi: 'Tối nay mình vui lắm!' },
  ],
  dialogue: [
    { who: 'A', en: 'Hey! I’m having a small party this Saturday. Can you come?', vi: 'Này! Thứ Bảy này mình tổ chức tiệc nhỏ. Bạn đến được không?' },
    { who: 'B', en: 'Sounds great! What’s the occasion?', vi: 'Tuyệt quá! Nhân dịp gì vậy?' },
    { who: 'A', en: 'I just got a new job, so I want to celebrate.', vi: 'Mình vừa có việc mới nên muốn ăn mừng.' },
    { who: 'B', en: 'Congratulations! What time should I come?', vi: 'Chúc mừng nhé! Mình nên đến lúc mấy giờ?' },
    { who: 'A', en: 'Around 6 p.m. Just bring yourself — food and drinks are ready!', vi: 'Khoảng 6 giờ tối. Cứ đến thôi — đồ ăn thức uống có sẵn rồi!' },
    { who: 'B', en: 'Perfect. I’ll bring a little gift anyway. See you Saturday!', vi: 'Tuyệt. Nhưng mình vẫn sẽ mang quà nhỏ. Hẹn thứ Bảy nhé!' },
  ],
},
{
  id: 'technology', icon: '📱', level: 3,
  name: 'Công nghệ & Mạng xã hội',
  nameEn: 'Technology & Social Media',
  vocab: [
    { w: 'download', ipa: '/ˌdaʊnˈloʊd/', m: 'tải xuống', ex: 'You can download the app for free.' },
    { w: 'password', ipa: '/ˈpæswɜːrd/', m: 'mật khẩu', ex: 'I forgot my password again.' },
    { w: 'wifi', ipa: '/ˈwaɪfaɪ/', m: 'mạng không dây', ex: 'What’s the wifi password here?' },
    { w: 'charge', ipa: '/tʃɑːrdʒ/', m: 'sạc pin', ex: 'My phone needs charging.' },
    { w: 'post', ipa: '/poʊst/', m: 'đăng bài', ex: 'She posted photos of her trip.' },
    { w: 'follow', ipa: '/ˈfɑːloʊ/', m: 'theo dõi', ex: 'Follow me on Instagram!' },
    { w: 'video call', ipa: '/ˈvɪdioʊ kɔːl/', m: 'gọi video', ex: 'Let’s have a video call tonight.' },
    { w: 'update', ipa: '/ˌʌpˈdeɪt/', m: 'cập nhật', ex: 'You should update your phone.' },
  ],
  phrases: [
    { en: 'What’s the wifi password?', vi: 'Mật khẩu wifi là gì vậy?' },
    { en: 'My battery is running low.', vi: 'Điện thoại mình sắp hết pin.' },
    { en: 'Can I borrow your charger?', vi: 'Cho mình mượn sạc được không?' },
    { en: 'Are you on Facebook?', vi: 'Bạn có dùng Facebook không?' },
    { en: 'Send me the photos, please.', vi: 'Gửi mình mấy tấm ảnh nhé.' },
    { en: 'Let’s take a selfie together!', vi: 'Chụp selfie cùng nhau đi!' },
  ],
  dialogue: [
    { who: 'A', en: 'Excuse me, is there free wifi in this café?', vi: 'Cho hỏi quán này có wifi miễn phí không ạ?' },
    { who: 'B', en: 'Yes, the password is on the receipt.', vi: 'Có ạ, mật khẩu in trên hóa đơn.' },
    { who: 'A', en: 'Perfect. Oh no, my phone is almost dead.', vi: 'Tuyệt. Ôi không, điện thoại mình sắp hết pin rồi.' },
    { who: 'B', en: 'There’s a charging port under every table.', vi: 'Dưới mỗi bàn đều có cổng sạc đấy ạ.' },
    { who: 'A', en: 'That’s so convenient! This place is great.', vi: 'Tiện quá! Quán này tuyệt thật.' },
    { who: 'B', en: 'Thank you! Don’t forget to follow our page for discounts.', vi: 'Cảm ơn anh! Đừng quên theo dõi trang của quán để nhận ưu đãi nhé.' },
  ],
},
{
  id: 'emergency', icon: '🚨', level: 3,
  name: 'Tình huống khẩn cấp',
  nameEn: 'Emergencies',
  vocab: [
    { w: 'help', ipa: '/help/', m: 'giúp đỡ', ex: 'Help! Somebody call the police!' },
    { w: 'accident', ipa: '/ˈæksɪdənt/', m: 'tai nạn', ex: 'There was an accident on the highway.' },
    { w: 'ambulance', ipa: '/ˈæmbjələns/', m: 'xe cứu thương', ex: 'Call an ambulance, quickly!' },
    { w: 'police', ipa: '/pəˈliːs/', m: 'cảnh sát', ex: 'The police arrived in five minutes.' },
    { w: 'lost', ipa: '/lɔːst/', m: 'bị lạc, bị mất', ex: 'I’m lost. Can you help me?' },
    { w: 'stolen', ipa: '/ˈstoʊlən/', m: 'bị đánh cắp', ex: 'My wallet was stolen.' },
    { w: 'fire', ipa: '/ˈfaɪər/', m: 'hỏa hoạn, lửa', ex: 'Fire! Everybody get out!' },
    { w: 'embassy', ipa: '/ˈembəsi/', m: 'đại sứ quán', ex: 'Contact your embassy if you lose your passport.' },
  ],
  phrases: [
    { en: 'Help! I need a doctor!', vi: 'Cứu với! Tôi cần bác sĩ!' },
    { en: 'Please call an ambulance.', vi: 'Làm ơn gọi xe cứu thương.' },
    { en: 'My passport has been stolen.', vi: 'Hộ chiếu của tôi bị đánh cắp.' },
    { en: 'I’d like to report a theft.', vi: 'Tôi muốn trình báo một vụ trộm.' },
    { en: 'I’m lost. Could you show me on the map?', vi: 'Tôi bị lạc. Chỉ giúp tôi trên bản đồ được không?' },
    { en: 'Is there a police station near here?', vi: 'Gần đây có đồn cảnh sát không?' },
  ],
  dialogue: [
    { who: 'A', en: 'Excuse me! I need help. My bag was stolen.', vi: 'Xin lỗi! Tôi cần giúp đỡ. Túi của tôi bị trộm mất rồi.' },
    { who: 'B', en: 'I’m sorry to hear that. What was inside?', vi: 'Rất tiếc khi nghe vậy. Trong túi có gì ạ?' },
    { who: 'A', en: 'My wallet, phone, and passport.', vi: 'Ví, điện thoại và hộ chiếu của tôi.' },
    { who: 'B', en: 'You should report it to the police station. It’s two blocks away.', vi: 'Anh nên trình báo ở đồn cảnh sát. Cách đây hai dãy nhà thôi.' },
    { who: 'A', en: 'Could you come with me? My English is not very good.', vi: 'Bạn đi cùng tôi được không? Tiếng Anh tôi không tốt lắm.' },
    { who: 'B', en: 'Of course. And you should also call your embassy about the passport.', vi: 'Tất nhiên rồi. Anh cũng nên gọi đại sứ quán về vụ hộ chiếu nữa.' },
  ],
},
{
  id: 'smalltalk', icon: '☕', level: 3,
  name: 'Small Talk — Trò chuyện xã giao',
  nameEn: 'Small Talk',
  vocab: [
    { w: 'by the way', ipa: '/baɪ ðə weɪ/', m: 'nhân tiện', ex: 'By the way, have you seen the new movie?' },
    { w: 'actually', ipa: '/ˈæktʃuəli/', m: 'thật ra', ex: 'Actually, I’ve never been there.' },
    { w: 'recently', ipa: '/ˈriːsntli/', m: 'gần đây', ex: 'Have you watched anything good recently?' },
    { w: 'sounds good', ipa: '/saʊndz ɡʊd/', m: 'nghe hay đấy', ex: 'Coffee at 3? Sounds good!' },
    { w: 'catch up', ipa: '/kætʃ ʌp/', m: 'hàn huyên, cập nhật', ex: 'Let’s catch up over lunch.' },
    { w: 'long time no see', ipa: '/lɔːŋ taɪm noʊ siː/', m: 'lâu rồi không gặp', ex: 'Hey! Long time no see!' },
    { w: 'keep in touch', ipa: '/kiːp ɪn tʌtʃ/', m: 'giữ liên lạc', ex: 'Let’s keep in touch!' },
    { w: 'take care', ipa: '/teɪk ker/', m: 'bảo trọng', ex: 'Goodbye! Take care!' },
  ],
  phrases: [
    { en: 'Long time no see! How have you been?', vi: 'Lâu quá không gặp! Dạo này bạn thế nào?' },
    { en: 'Same as usual. How about you?', vi: 'Vẫn vậy thôi. Còn bạn?' },
    { en: 'Have you seen any good movies lately?', vi: 'Gần đây có xem phim gì hay không?' },
    { en: 'By the way, how’s your family?', vi: 'Nhân tiện, gia đình bạn khỏe chứ?' },
    { en: 'It was great catching up with you!', vi: 'Rất vui được hàn huyên với bạn!' },
    { en: 'Let’s keep in touch. Take care!', vi: 'Giữ liên lạc nhé. Bảo trọng!' },
  ],
  dialogue: [
    { who: 'A', en: 'Duong? Is that you? Long time no see!', vi: 'Dương? Bạn đấy à? Lâu quá không gặp!' },
    { who: 'B', en: 'Oh wow, Sarah! It must be two years! How have you been?', vi: 'Ồ, Sarah! Chắc phải hai năm rồi! Dạo này bạn thế nào?' },
    { who: 'A', en: 'Pretty good! I just moved back to the city. And you?', vi: 'Khá tốt! Mình vừa chuyển về lại thành phố. Còn bạn?' },
    { who: 'B', en: 'Busy with work, but I can’t complain. Are you free now? Let’s grab a coffee.', vi: 'Bận việc suốt, nhưng cũng ổn. Giờ bạn rảnh không? Đi cà phê đi.' },
    { who: 'A', en: 'Sounds good! There’s a nice café around the corner.', vi: 'Nghe hay đấy! Có quán cà phê xinh lắm ngay góc phố.' },
    { who: 'B', en: 'Perfect. We have so much to catch up on!', vi: 'Tuyệt. Bọn mình có bao nhiêu chuyện để hàn huyên!' },
  ],
},
];
